### ISSUE TITLE
Analyzing stereo files takes twice the time of mono files

### ISSUE THREAD

**Issue by fegue** [kahst/BirdNET-Analyzer#10]
The code clearly loads audio files as mono in audio.py
Do you have any idea why BirdNET still takes twice the time?

This happens on a RaspberryPi 3A+
Memory usage is similar when analyzing mono files.
The function librosa.load(..., mono = True) executes almost instantaneously

**Comment by kahst** [comment]
Did you find a solution or workaround for that issue? Haven't been able to reproduce the behavior so far.

**Comment by mzakharo** [comment]
@fegue  -> try placing the  audio files into /tmp ramdisk, and analyzing from there, trying to rule out the SD card reads. Also, if you are using client/server.py, then server saves temporary file to local folder, again,  you can edit the file to move it to /tmp.
