### ISSUE TITLE
train.py TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by paminaw** [kahst/BirdNET-Analyzer#103]
I am having trouble training the model since the same Error keeps coming up: TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given - how can I solve this?

**Comment by rumeltr** [comment]
I encountered this error as well and was able to make it go away by adding another set of parentheses around the arguments after “sig” in the call to np.hstack on line 64 of audio.py; these are present in the call to np.hstack on line 48 which does not throw the same error. Unfortunately I’m not experienced enough with the git system to know how to submit a pull request from a branch so I haven’t been able to suggest this change.

**Comment by paminaw** [comment]
Thank you for the fast reply! I added the parentheses but now I am getting an new AttributeError: 'str' object has no attribute 'shape' regarding: 

BirdNET-Analyzer/model.py", line 282, in embeddings
    INTERPRETER.resize_tensor_input(INPUT_LAYER_INDEX, [len(sample), *sample[0].shape])

I'm very new with this coding language, but from what I understand he thinks something in this code is a string while it should be a numpy array(?) - how can I change this?

**Comment by kahst** [comment]
Hmmm, hard to tell. Sounds like maybe an input file was corrupted and ended up as "empty" sample...Have you tried using the train set we provided? Does the error also occur when using the provided data? If so, can you please post a full stack trace?

**Comment by Josef-Haupt** [comment]
There were indeed some misplaces parenthesis, just be fixed following this commit 3c951480e8b922aec87b0e28131837da0e053792
