### ISSUE TITLE
Discrepancies in detections compared to https://birdnet.cornell.edu/api/

### ISSUE THREAD

**Issue by ivoba** [kahst/BirdNET-Analyzer#109]
Hi,
i noticed that this model detects differently than https://birdnet.cornell.edu/api/.
The results seem to be not as accurate and sometimes false.
F.e. i have a file that is detected as Eurasian Skylark in the old model (i suppose it is still in use in https://birdnet.cornell.edu/api/) but the new model here detects a Eurasian Siskin, which is incorrect.

I suppose the model is not complete yet resp. not as complete as the old tflite model, as i read here:
https://github.com/kahst/BirdNET-Analyzer/issues/20#issuecomment-1108866546

Maybe there should be a warning in the readme about the state of the model.
`most advanced version of BirdNET` is probably from a technical perspective and not from the actual detection capabilities.

**Comment by kahst** [comment]
The API still uses a very old version of the model, which we last updated in 2019, so I am not surprised about the differences. Yet, ideally, the newer model would predict the correct species, but I guess, sometimes things improve and others do not when updating a model.
