### ISSUE TITLE
Rename Python distribution from birdnetlib to birdnet

### ISSUE THREAD

**Issue by Bengt** [kahst/BirdNET-Analyzer#121]
This name would be less surprising and is still available on PyPI:

https://pypi.org/search/?q=birdnet

**Comment by LimitlessGreen** [comment]
That's because `birdnetlib` is a project on it's own.
https://github.com/joeweiss/birdnetlib

It's not directly related to **BirdNET-Analyzer**.

I think this issue can be closed.

**Comment by kahst** [comment]
Yes, `birdnetlib` is an independent project. However, we'll work with Joe (the developer) in the future to make `birdnetlib` the official Python package.

**Comment by LimitlessGreen** [comment]
Great to hear!

One thing I've always missed in the original project is having a Python binding. It's only possible to get an output in form of files from BirdNet-Analyzer. However, obtaining something simple, like a dictionary of labels, is not, without rewriting the code.
