### ISSUE TITLE
NOOB question on installation 

### ISSUE THREAD

**Issue by MMUTom** [kahst/BirdNET-Analyzer#125]
I have having an issue running the 'Multiple Files' option in the GUI. The 'single file' option works OK.  

When I select the 'multiple files tab' and select the directory that I want it to use,  it provides an error. 

The 'trace window' shows the following .. 

Traceback (most recent call last):
  File "gradio\routes.py", line 394, in run_predict
  File "gradio\blocks.py", line 1078, in process_api
  File "gradio\blocks.py", line 1012, in postprocess_data
  File "gradio\components.py", line 2767, in postprocess
IndexError: list index out of range

I installed the software using the windows installer on a window 10 OS. I unblocked the zip as requested. 

As I said the program operates with no errors when I use the 'single file' option. 

Any thoughts please?

Tom

**Comment by Josef-Haupt** [comment]
Hi! I just tested it on my end, and it seems to work.
Can you share all the settings you used and the file structure in your selected directory (if thats not too much to ask)?

**Comment by MMUTom** [comment]
Hopefully this is what you need. 

Data is on C:\Temp\20230518\ where the files are named '20230518_030800.wav' etc
Application is under C:\BirdNet\BirdNET-Analyzer\BirdNET-Analyzer\'application'

![image](https://github.com/kahst/BirdNET-Analyzer/assets/134394497/c5017556-c98e-4296-a306-51a2864fdfe5)

**Comment by Josef-Haupt** [comment]
Thanks! There still seems to be a bug, when no audio files are found in your selected directory (Fixing it right now).
So it seems to me as if the files can't be read, maybe because of missing permissions (it might be a system directory).

**Comment by Josef-Haupt** [comment]
Good point! That's definitly a bug

**Comment by MMUTom** [comment]
Appreciate your help on the matter - many thanks
