### ISSUE TITLE
How to calculate week number?

### ISSUE THREAD

**Issue by emoritzx** [kahst/BirdNET-Analyzer#128]
According to the [README](https://github.com/kahst/BirdNET-Analyzer/blob/main/README.md):

> Week of the year when the recording was made. Values in [1, 48] (4 weeks per month). Set -1 for year-round species list.

However, when using Python's [datetime.date.isocalendar](https://docs.python.org/3/library/datetime.html#datetime.date.isocalendar):

> The ISO year consists of 52 or 53 full weeks, and where a week starts on a Monday and ends on a Sunday. The first week of an ISO year is the first (Gregorian) calendar week of a year containing a Thursday. This is called week number 1, and the ISO year of that Thursday is the same as its Gregorian year.

As a naive implementation, I am scaling the ISO week to the BirdNET week:

```python
ISO_WEEKS = 52
BIRDNET_WEEKS = 48

now = datetime.datetime.now()
iso_week = now.isocalendar().week
birdnet_week = math.floor((iso_week * BIRDNET_WEEKS) / ISO_WEEKS)
```

But I was wondering if there is a better calculation to use to more closely align with what the model is expecting.

**Comment by rexxars** [comment]
I think this may be the right way? (Javascript, but you get the idea)

```js
const date = new Date('2022-12-31T12:00:00Z');
const dayOfMonth = date.getDate();

// Note: getMonth() returns 0 through 11, not 1 through 12
const weekOfYear = (date.getMonth()) * 4;

let week;

if (dayOfMonth <= 7) {
    week = weekOfYear + 1;
} else if (dayOfMonth <= 14) {
    week = weekOfYear + 2;
} else if (dayOfMonth <= 21) {
    week = weekOfYear + 3;
} else if (dayOfMonth >= 22) {
    week = weekOfYear + 4;
}

console.log(week);
```

**Comment by kahst** [comment]
There is no nice conversion, eBird simply assumes that each month has 4 weeks and so weeks 1-4 are January, 5-8 are February and so on. However, the species range model estimates the likely species even if the exact week is not given, so it should work fine even if you are 1-2 weeks off.
