### ISSUE TITLE
Lat Long switch?

### ISSUE THREAD

**Issue by sergewich** [kahst/BirdNET-Analyzer#129]
Hi,
In the windows GUI the lat goes from -180 to 180 and the long from -90 to 90. I am a bit puzzled by that as I thought lat is -90 to 90 and long -180 to 180. I am trying to set the correct coordinates for Singapore and am unsure how to do this. Can you help out? 
And perhaps also let me know which species from that region are in the model? Is there a list I can check for that?
Best,
Serge

**Comment by sergewich** [comment]
I agree but in the GUI that I downloaded from GitHub for windows the lat goes to 180 and the long to 90! So I can’t put Singapore in and also do not know how this then links to the database? Sent from my iPhone. Please ignore typos. On 26 May 2023, at 10:30, Josef Haupt ***@***.***> wrote:﻿
It's the otherway round, lat goes from -90 to 90 and long from -180 to 180. Don't know an exact source for this, but here are some References 1, 2.
Singapur should be at ca. 1.3 lat and 103.8 long.
You can check the species from that region with the species.py.
For example py .\species.py --o spcies_list_singapore.txt --lat 1.3 --lon 103.8.
You can also change the threshold, by default its is 0.05, to narrow the list down to the species the model ist most confident in.

**Comment by Josef-Haupt** [comment]
Ah you're right, that's definitly a bug!
I'll fix it right now, it will be included in the next release.
You could use the `--lat` and `--lon` switches in the `analyze.py` manually as a workaround for now.

**Comment by sergewich** [comment]
Many thanks. It would be great if you can let me know when the next 
release will be. The XPrize is starting and I would like to use this 
over there.

I am not sure where the analyse.py is? Is that in the GUI somewhere?

------ Original Message ------
From: "Josef Haupt" ***@***.***>
To: "kahst/BirdNET-Analyzer" ***@***.***>
Cc: "sergewich" ***@***.***>; "Author" 
***@***.***>
Sent: 26/05/2023 12:17:29
Subject: Re: [kahst/BirdNET-Analyzer] Lat Long switch? (Issue #129)

**Comment by sergewich** [comment]
Hi,

I downloaded it again as I was not sure whether it was fixed now but it 
still is the same issue. Is that correct? Sorry for another email about 
this.

Best,

Serge

------ Original Message ------
From: "Josef Haupt" ***@***.***>
To: "kahst/BirdNET-Analyzer" ***@***.***>
Cc: "sergewich" ***@***.***>; "Author" 
***@***.***>
Sent: 26/05/2023 12:49:32
Subject: Re: [kahst/BirdNET-Analyzer] Lat Long switch? (Issue #129)

**Comment by sergewich** [comment]
I think I understand now that I just have to run the gui from python and it will be ok but that the windows download zip is not updated yet. Is that the case? Sent from my iPhone. Please ignore typos. On 26 May 2023, at 12:49, Josef Haupt ***@***.***> wrote:﻿
Closed #129 as completed via #130.

**Comment by Josef-Haupt** [comment]
For future reference:
When a pull request is completed (a bug fixed) it is first and foremost in code only.
Periodically we will build the application with the fixed code and update the download.
So if you want the most current app, you can always use the `gui.py`, as you've seen already.

You try to download again now, the zip should contain the fixed GUI

**Comment by sergewich** [comment]
Many thanks. That is clear.One more question if you do not mind. If I select a location does it only use the species from that location or also within a certain radius around it? Sent from my iPhone. Please ignore typos. On 26 May 2023, at 13:41, Josef Haupt ***@***.***> wrote:﻿
For future reference:
When a pull request is completed (a bug fixed) it is first and foremost in code only.
Periodically we will build the application with the fixed code and update the download.
So if you want the most current app, you can always use the gui.py, as you've seen already.
You try to download again now, the zip should contain the fixed GUI

**Comment by sergewich** [comment]
And many thanks for the super fast fix! Sent from my iPhone. Please ignore typos. On 26 May 2023, at 14:45, Serge Wich ***@***.***> wrote:﻿Many thanks. That is clear.One more question if you do not mind. If I select a location does it only use the species from that location or also within a certain radius around it? Sent from my iPhone. Please ignore typos. On 26 May 2023, at 13:41, Josef Haupt ***@***.***> wrote:﻿
For future reference:
When a pull request is completed (a bug fixed) it is first and foremost in code only.
Periodically we will build the application with the fixed code and update the download.
So if you want the most current app, you can always use the gui.py, as you've seen already.
You try to download again now, the zip should contain the fixed GUI
