### ISSUE TITLE
typing syntax invalid for python < 3.8

### ISSUE THREAD

**Issue by emoritzx** [kahst/BirdNET-Analyzer#132]
https://github.com/kahst/BirdNET-Analyzer/blob/f39eb842360c6e3ed3b24d45dddf46e726e85f90/config.py#L115

This syntax is only valid for Python >= 3.9. For 3.8 and earlier, you get an error message:
> TypeError: 'type' object is not subscriptable

Update documentation and Dockerfile to require at least python 3.9.

**Comment by Josef-Haupt** [comment]
Yes youre right about the typings. The documentation is already up to date, but the docker file needs to be updated.
