### ISSUE TITLE
V2.4 doesn´t work

### ISSUE THREAD

**Issue by HGFestl** [kahst/BirdNET-Analyzer#137]
Hello, I tried to run the new BirdNET version V2.4, but I got the following error:

Traceback (most recent call last):
  File "analyze.py", line 13, in <module>
    import audio
  File "/root/BirdNET-Analyzer/audio.py", line 5, in <module>
    import config as cfg
  File "/root/BirdNET-Analyzer/config.py", line 115, in <module>
    LABELS: list[str] = []
TypeError: 'type' object is not subscriptable

Is there any idea for this? Which more information about this is needed?

Best regards, Hans Guenter

**Comment by Josef-Haupt** [comment]
This is a typing issue, since Python 3.9, the native types can be used for ducktyping, but it will throw this error for Python <3.9
So the easiest fix is to use Python 3.9 for this repo,.

**Comment by HGFestl** [comment]
Thank you, Josef!
