### ISSUE TITLE
Clarification: Custom Species List 

### ISSUE THREAD

**Issue by MMUTom** [kahst/BirdNET-Analyzer#138]
Operational question 

Can somebody clarify the operation of the custom species list. 
It could operate by
a) restricting the output (text) files to only include the instances found of the birds in the custom species list
b) only apply the DNN training algorithm for those birds in the custom species list to the collected data set
c)?

at the moment I think that it is a) but could somebody comment please?

T

**Comment by kahst** [comment]
Yes, it is a). The output of the neural network is fixed and produces probability scores for all species all the time. A custom species list acts as a filter to only show scores and detections of species on that list. This is simply a binary filter.
