### ISSUE TITLE
Frequency to high for RavenPro

### ISSUE THREAD

**Issue by psubraty** [kahst/BirdNET-Analyzer#140]
2.4 Birdnet has higher frequency range, up to 15000. When I try to open result files in RavenPro 1.6 I get an error, that frequency should not be higher than 12000. I have to manually change all 15000 to 12000 in text files.
![Zrzut ekranu 2023-06-06 121900](https://github.com/kahst/BirdNET-Analyzer/assets/127944510/c563c26d-4a1f-433d-a216-710305323410)

**Comment by J-NP** [comment]
Hi, 
I have the same problem with Mac or Windows machines, from the GUI or not. I change the files in R... but that's not very convenient. Any solution?
Thanks!
