### ISSUE TITLE
Why is the 8-bit tflite model larger than the 16-bit model?

### ISSUE THREAD

**Issue by jfswitzer** [kahst/BirdNET-Analyzer#141]
more of a question than an issue but I noticed that the 16-bit tflite model (checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP16.tflite) is 24.7 MB while the 8-bit model (checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_INT8.tflite) is 39.2 MB

Why is this?

**Comment by kahst** [comment]
The 8-bit model is not a fully-quantized model, but instead uses mixed precision. TFLite seems to mix 8-bit and 32-bit, which makes the 8-bit model a bit larger than the 16bit model, which only uses 16-bit precision. However, the 8-bit model is still faster on dedicated hardware that supports 8-bit precision (e.g., Raspberry Pi or mobile phones) and should be used in those scenarios.
