### ISSUE TITLE
GUI.py is looking for xkb in conda's shared files

### ISSUE THREAD

**Issue by kdarras** [kahst/BirdNET-Analyzer#145]
Not sure whether this is a bug or whether I messed up something when installing batdetect2, but since I did (and it was installed in its own virtual environment), when I run gui.py, I get the following error:

xkbcommon: ERROR: failed to add default include path /home/kdarras/anaconda3/share/X11/xkb

I managed to install X11 in conda, and also xkbcommon, but nothing gets added to this folder, so gui.py keeps trying to access the files in this non-existing folder...

Any idea how I could solve this problem?

I am using v2.2 for replicating a colleague's results.

**Comment by Josef-Haupt** [comment]
This doesn't seem to be a BirdNET problem. If you have further information, let us know
