### ISSUE TITLE
Wheres my audios- on Windows, No problem.

### ISSUE THREAD

**Issue by Cheeserdog** [kahst/BirdNET-Analyzer#147]
Have been trying for 2 years to find a directory link to my Birdnet song file- over 200 of them on the same phone- if I had my Nokia, in seconds I'd retrieved them. But noone at cornell seems to be able give a straight, easy link for androids- it's my observations and I need them, even if I hadn't got a much better phone. Thanks

**Comment by nishantnnb** [comment]
In show observations, we can export single or all observations (recordings).

**Comment by Andx667** [comment]
To elaborate a bit on the previous comment:
Open the BirdNet App, open the Menu on the top left and select "show recordings" (or similar, im on a german phone), then open the 3-dots-Menu on the top right and select "export recordings". If BirdNet has access to your Downloads Folder it will copy all recordings to this folder. From there it should be easy to copy them to a PC or use them in another way.

**Comment by Josef-Haupt** [comment]
On a different note, BirdNET the App is something entirely different than the BirdNET-Analyzer repo.

**Comment by Cheeserdog** [comment]
ThanksOn Jun 27, 2023 3:10 AM, Andx ***@***.***> wrote:
To elaborate a bit on the previous comment:
Open the BirdNet App, open the Menu on the top left and select "show recordings" (or similar, im on a german phone), then open the 3-dots-Menu on the top right and select "export recordings". If BirdNet has access to your Downloads Folder it will copy all recordings to this folder. From there it should be easy to copy them to a PC or use them in another way.

**Comment by Cheeserdog** [comment]
Sorry top left "show observations" then a window with recording list comes up with No 3 dots. See my problem- no export optionOn Jun 27, 2023 3:10 AM, Andx ***@***.***> wrote:
To elaborate a bit on the previous comment:
Open the BirdNet App, open the Menu on the top left and select "show recordings" (or similar, im on a german phone), then open the 3-dots-Menu on the top right and select "export recordings". If BirdNet has access to your Downloads Folder it will copy all recordings to this folder. From there it should be easy to copy them to a PC or use them in another way.

**Comment by Cheeserdog** [comment]
On Jun 27, 2023 3:10 AM, Andx ***@***.***> wrote:
To elaborate a bit on the previous comment:
Open the BirdNet App, open the Menu on the top left and select "show recordings" (or similar, im on a german phone), then open the 3-dots-Menu on the top right and select "export recordings". If BirdNet has access to your Downloads Folder it will copy all recordings to this folder. From there it should be easy to copy them to a PC or use them in another way.

**Comment by Cheeserdog** [comment]
Sorry top left "show observations" then a window with recording list comes up with No 3 dots. See my problem- no export optionOn Jun 26, 2023 10:39 PM, nishantnnb ***@***.***> wrote:
In show observations, we can export single or all observations (recordings).
