### ISSUE TITLE
I'd love to train a bat classifier

### ISSUE THREAD

**Issue by drbkimmel** [kahst/BirdNET-Analyzer#148]
I just attended Weekend at Sapsucker Woods and spoke with Lea Bouffaut about BirdNet.  I have 5 TB of bat data from Loudoun County VA and would like to make a classifier for our local bats.  The commercially available software is reasonable for getting to the resolution of a month but to get to a finer resolution (day or hour) the accuracy of the auto ids needs to improve.  To get to the resolution of one day I currently have to manually vet spectrograms.  

Lea mentioned that some initial work with bat recordings had been attempted but that the recordings have to be slowed down to fit the frequency restriction.  Do you think it would be possible/worth it for me to make a bat call classifier using BirdNet?  How difficult would it be to shift the working frequency range of BirdNet to say 18kHz-125kHz?

Thanks,
Bruce Kimmel

**Comment by fegue** [comment]
Currently, BirdNET resamples all audio data to 48 kHz and the frequency range is 0 Hz to 15 kHz. The creation of the spectrograms is also part of the NN. Changing the frequency range entails substantial changes. 
However, it now uses a two-channel spectrogram, with one channel covering 0 Hz to 3 kHz and the other 500 Hz to 15 kHz. So at some point, we might see a third channel covering higher frequency ranges. 

We know the need is there, but we don't have a roadmap yet.

I do not know of any workarounds but please let us know if you find one that works for you :)
