### ISSUE TITLE
Add time to segments

### ISSUE THREAD

**Issue by gitalm** [kahst/BirdNET-Analyzer#149]
Dear @kahst  and all your team,

thanks for the wonderful work. In segments.py the files are saved with the original file name, the confidence and a number.
Would it be possible to add the actual time of the recording, by using the modification date and add the seconds from start?

Pseudocode like 
`import datetime
datetime.datetime.fromtimestamp(os.path.getmtime("SMM09889_20230625_211402.wav")+START).strftime('%c')`

Wav-Files are not longer than 1h and so the exact time for controlling the results would easily be seen. Thanks

**Comment by Josef-Haupt** [comment]
Although it the current segment file name could be optimized, to use the the modification date as a base is a very specialized use case for most people.
Something like this could be implemented in a script that runs afterwards and updates the names to your desired format.
