### ISSUE TITLE
Add samples to an existing class in BirdNET instead of replacing the class. 

### ISSUE THREAD

**Issue by blegottesman** [kahst/BirdNET-Analyzer#151]
An idea for a new feature for the BirdNET analyzer: The ability to add samples to a class rather than replacing the class. If the user-added sounds have the same class name as one of the existing classes, those samples woudl get merged instead of replaced? (e.g. let's say that BirdNET has 20 toucan sounds and I want to add 20 more).

**Comment by Josef-Haupt** [comment]
It is not possible right now.
You could train your own classifier with your data and use BirdNET, as well as your custom classifier in parallel.
