### ISSUE TITLE
Latest XenoCanto/Macaulay lib recording that was used to train BirdNET-Analyzer v2.4 ? 

### ISSUE THREAD

**Issue by DD4WH** [kahst/BirdNET-Analyzer#152]
We are currently testing BN-Analyzer vs BirdNET-Lite and other models for classification of specific bird species.

In the process of setting up the test data set with audio files from XenoCanto and Macaulay library we would like to prevent to include WAV files in our manually annoted test data set that had been used for the training of v2.4

Could you give us the last XenoCanto number and/or the last date up to which recordings could have potentially been included in the training set for BirdNET-Analyzer v2.4 ?

Thanks in advance !

Frank Dziock

**Comment by kahst** [comment]
Sorry it took me so long Frank, the highest XC number we used for training in V2.4 is 694204 and for Macaulay Library it is 399952111.

**Comment by DD4WH** [comment]
Thanks Stefan, that helps us a lot !
