### ISSUE TITLE
Error: Cannot open audio file

### ISSUE THREAD

**Issue by paminaw** [kahst/BirdNET-Analyzer#153]
Hello! 
I'm trying to set up BirdNet-Analyzer on my Mac using an M2 Chip. I am currently having the issue that I cannot analyze any audios due to "Error: Cannot open audio file". The file definitely exists in the correct directory and is a wav.file. Im using the newest python version but it still won't work. 
I've managed using BirdNet-Analyzer on the same Macbook in the past but now I can't seem to be getting rid of this Error Message. How can I resolve this issue?

**Comment by sara-keen** [comment]
Hi! I am also a mac with an M2 chip and I encountered the same issue. I'd love to help debug, what other information can I provide to help?

As in the above comment, I am sure the sound file exists locally. Thanks for any suggestions!

**Comment by Andx667** [comment]
hi,

as a start we would need:
MacOS Version
Python Version
(anonymous) Path to the birdnet-analyzer and the file location
anything on your side that might have changed since the last time you used birdnet-analyzer

we sadly dont have many Mac devices to debug on, but with this information we can try. 

Thanks for your help!

**Comment by Josef-Haupt** [comment]
Hi, could you check if your analyzer directory contrains an `error_log.txt` file.
If so please send us the contents, as it should contain the actual error,

**Comment by sara-keen** [comment]
Sure, here are the contents of error_log.txt:

Traceback (most recent call last):
  File "/Users/sara/BirdNET-Analyzer/analyze.py", line 257, in analyzeFile
    chunks = getRawAudioFromFile(fpath)
  File "/Users/sara/BirdNET-Analyzer/analyze.py", line 206, in getRawAudioFromFile
    sig, rate = audio.openAudioFile(fpath, cfg.SAMPLE_RATE)
  File "/Users/sara/BirdNET-Analyzer/audio.py", line 25, in openAudioFile
    import librosa
ModuleNotFoundError: No module named 'librosa'

Traceback (most recent call last):
  File "/Users/sara/BirdNET-Analyzer/analyze.py", line 257, in analyzeFile
    chunks = getRawAudioFromFile(fpath)
  File "/Users/sara/BirdNET-Analyzer/analyze.py", line 206, in getRawAudioFromFile
    sig, rate = audio.openAudioFile(fpath, cfg.SAMPLE_RATE)
  File "/Users/sara/BirdNET-Analyzer/audio.py", line 25, in openAudioFile
    import librosa
ModuleNotFoundError: No module named 'librosa'

**Comment by sara-keen** [comment]
Thought I had librosa installed locally already, will do that and it should fix the error.

**Comment by vanderleidebastiani** [comment]
Hi,

I had a similar error on Mac (Intel-based). In my case, the resampy library was missing. This was specified in the file error_log.txt 

Best, Vanderlei
