### ISSUE TITLE
Worse results using a custom classifier generated by training on top of BirdNET

### ISSUE THREAD

**Issue by gls21** [kahst/BirdNET-Analyzer#157]
Hi,

I am trying to analyse some recording files from Argentina but need to improve the model as the BirdNET default model is not performing well on this data set. I am using birdnetlib so I can write and run scripts in Python, rather than running python from the terminal. 

I am practicing training BirdNET with the sample training data set provided (while I wait for real training data to be sent). I have successfully made the Custom_Classifier.tflite and Custom_Classifier_Labels.txt files. However, when I use these files as my custom classifier, it results in no detections (whereas I was getting some before with the default model).

I'm not sure I entirely understand how training BirdNET and using a custom classifier works. I was assuming the model would still be able to recognise all the species in the default model plus the new ones I have trained it on? But the fact that I get no detections with the custom classifier conflicts this? 

I am also confused whether there is a difference between a species list and 'labels'? Does the Custom_Classifier_Labels.txt replace the species list file, or are both needed?

Below is a screenshot of the start of the output produced when I run BirdNET with the custom classifier - I am confused why it says 'load model - False' followed by 'Model loaded'
![image](https://github.com/kahst/BirdNET-Analyzer/assets/91906620/851ed4e7-de51-4bca-b574-b8275bbeae4e)

Any advice on these points would be much appreciated.

Many thanks,
Grace

**Comment by WarblerWayne** [comment]
I've been having similar results using a custom classifier and I'm curious what the answer here is.

**Comment by Josef-Haupt** [comment]
The custom classifier does only detect the species it was trained on and not all species which are included in the BirdNET classifier.
You just train the last layer with the new data, while the other layers have been trained with all BirdNET species.

**Comment by Josef-Haupt** [comment]
You can currently append your custom classifier to BirdNET to get the output of both.
Please get back to us if the issue still exists with the current version.
