### ISSUE TITLE
Include a self-signed certificate in fully packaged Windows version

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#160]
Many corporate and government settings have restrictions on using unsigned executables, but the fully packaged Windows version seems important for increasing easy access to BirdNET. Does Cornell / TUC / development team have a self-signing certificate that could be used for the fully packaged Windows executable(s) (BirdNET-Analyzer.exe and BirdNET-Analyzer-GUI.exe)? This might make widespread access more straightforward and allow BirdNET to bypass flags that could otherwise make it prohibited. Aspiring users in this situation instead have to attempt the more complex modes of access (which, speaking from experience, may be concomitant with other IT hurdles and restrictions). Thank you for considering!

**Comment by Josef-Haupt** [comment]
Sadly we have no access to restricted win pcs to test it for ourselfes.
What exactly is the issue? Is it the smartscreen, that's complaining?

**Comment by cbalantic** [comment]
Hi @Josef-Haupt  @kahst 

Understood! The request in this case is not for diagnosis or troubleshooting. Our security software's current behavior is to block unsigned executables. As far as I'm aware, after many, many hours working with our IT department, we do not have any admin means to unblock or circumvent the behavior, so I'm curious as to whether your team would consider including digital signatures with the executables in the fully packaged Windows version.

For example, if an Audacity user were to navigate to the Audacity.exe on a Windows machine and right-click + Properties, they would see a tab with a digital signature like so: 
![image](https://github.com/kahst/BirdNET-Analyzer/assets/16154950/ebb5daa1-7825-4dac-8df9-3e797e08300e)

If you right-click + Properties for BirdNET-Analyzer.exe and BirdNET-Analyzer-GUI.exe, they do not come with a digital signature, which is why they are being blocked (the unblock instructions given in setup are not an option for us). For now, we are doggedly pursuing workarounds, but ultimately the lack of digital signature may soon prevent straightforward access/use of this groundbreaking tool by most federal land management agencies in the U.S. As such, I'm trying to advocate for access wherever I can -- the .exe fully packaged versions are likely the most easily accessible **free** way to use BirdNET for non-CS folks. I know you have a small team so I understand if it's a big ask, but maybe it's something to consider in future releases. Thank you so much for your work!

**Comment by Josef-Haupt** [comment]
We are working with the Cornell to sign the installer in the future, but the SmartScreen problem still remains.
