### ISSUE TITLE
Issue(s) with tflite-runtime / opening audio file on MacOS

### ISSUE THREAD

**Issue by drewsday** [kahst/BirdNET-Analyzer#162]
I was having trouble getting the "python analyze.py" command to run on a Mac.  I found this page:
https://stackoverflow.com/questions/74968761/pip3-cant-download-the-latest-tflite-runtime

and was able to install the version of tflite_runtime recommended on that page.

However, when I execute the "analyze.py" module, it only works with python3.9, and although it seems to run fine, it says it cannot open the example/soundscape.wav file.

`(birdnet-analyzer) M-E1026-9ML:BirdNET-Analyzer amorriso$ python3.9 analyze.py `
`Species list contains 6522 species`
`Found 1 files to analyze`
`Analyzing example/soundscape.wav`
`Error: Cannot open audio file example/soundscape.wav`

Ideas?

**Comment by Josef-Haupt** [comment]
There should be a `error_log.txt` file in your analyzer directory.
It contains the exact error message.

**Comment by drewsday** [comment]
Got it. Thanks!  The install instructions may need to be updated for MacOS to include installing librosa and the updated version of tflite_runtime.

Thanks again!
