### ISSUE TITLE
Issue in training with google colab 

### ISSUE THREAD

**Issue by nishantnnb** [kahst/BirdNET-Analyzer#163]
Hi, 
I am trying to use google colab for the first time to train data of sound samples of few birds .
Mounted google drive in colab where the birds sound data (training_data) as well as the contents (folders and files) of "BirdNET-Analyzer-main" are kept .
Following packages are installed.
pip install librosa resampy numpy==1.20
pip install tensorflow
pip install birdnetlib

To train the model, I am using following command:
!python drive/MyDrive/BirdNET-Analyzer-main/train.py --i drive/MyDrive/BirdNET-Analyzer-main/training_data/ --o drive/MyDrive/BirdNET-Analyzer-main/colab_saved_model/1.tflite

Initially it was giving some error regarding resampy module. Hence installed resampy again with separate command.
pip install resampy

Now while using the above command for training, it is giving following error for tflite model in the checkpoint. Following is the entire message after training started >>>
Loading training data...
Traceback (most recent call last):
  File "/content/drive/MyDrive/BirdNET-Analyzer-main/train.py", line 137, in <module>
    trainModel()
  File "/content/drive/MyDrive/BirdNET-Analyzer-main/train.py", line 80, in trainModel
    x_train, y_train, labels = _loadTrainingData()
  File "/content/drive/MyDrive/BirdNET-Analyzer-main/train.py", line 56, in _loadTrainingData
    embeddings = model.embeddings([sig])[0]
  File "/content/drive/MyDrive/BirdNET-Analyzer-main/model.py", line 378, in embeddings
    loadModel(False)
  File "/content/drive/MyDrive/BirdNET-Analyzer-main/model.py", line 46, in loadModel
    INTERPRETER = tflite.Interpreter(model_path=cfg.MODEL_PATH, num_threads=cfg.TFLITE_THREADS)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/interpreter.py", line 464, in __init__
    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
**ValueError: Could not open 'checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite'.**

Note 1)
BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite is already present in the same path: 
/content/drive/MyDrive/BirdNET-Analyzer-main/checkpoints/V2.4/

Note 2) 
On local machine, with python installed, I am able to train the model successfully (with same commands but different local paths as input).

Can someone kindly help with this?
Regards,
Nishant Bhagwat

**Comment by Josef-Haupt** [comment]
This might be a path issue, try specifying the full path in `config.py` -> `MODEL_PATH`.

**Comment by nishantnnb** [comment]
Hello Josef, 
Changing path in config.py file worked. 
 Thank you so much !
