### ISSUE TITLE
Windows installation error: numpy==1.20

### ISSUE THREAD

**Issue by prayagnshah** [kahst/BirdNET-Analyzer#165]
Hi all, 

I am an undergraduate student working at Environment and Climate Change Canada. I would like to raise an issue that, when I attempt to install BirdNET on biologists' computers, it consistently encounters an issue during the installation of `pip install numpy==1.20` after the recent BirdNET update. Error indicates that there has been no numpy package available. 

Error message: 

![image](https://github.com/kahst/BirdNET-Analyzer/assets/34435248/ad98c71f-2d2d-4365-871d-158648d3c07f)

When I try to dissect the command like:
1. pip install librosa
2. pip install resampy
3. pip install tensorflow 

After following these commands one by one, the program will work like a charm. I just wanted to raise this issue so that other Windows users can easily fix it. I spent hours installing it before discovering this solution.

Windows specifications where I was using for them:
* Windows 10 Enterprise
* i5-8th Generation
* 16 GB RAM
* 64 bit operating system

**Comment by Josef-Haupt** [comment]
Hi! Actually it should work without specifying the numpy version, since tensorflow also has a numpy dependency, the extra install step is not necessary.

**Comment by prayagnshah** [comment]
Yes @Josef-Haupt, while installing tensorflow it does install numpy==1.25 but was just getting confused due to the numpy==1.20. 

I will create a PR to correct that in ReadMe.
