### ISSUE TITLE
Question: Equivalent BirdNET Analyzer Model Version to App

### ISSUE THREAD

**Issue by hagachi** [kahst/BirdNET-Analyzer#173]
Thank you for developing and maintaining an excellent application! I'm using the latest BirdNet App iOS in the field to quickly check bird calls and then analyze our entire recordings after returning to the lab using BirdNet-Analyzer.  So, I'm interested in which version of BirdNet-Analyzer is equivalent to the App model.  Thank you in advance.

**Comment by max-mauermann** [comment]
The app actually uses two different models depending on wether you are in north-america/europe or anywhere else.

When not in NA/Europe the model used is the 3K-species App-model from the model-history is used (https://github.com/kahst/BirdNET-Analyzer/blob/main/checkpoints/README.md).

For NA/Europe an older implementation is used based on the original birdnet-repo (https://github.com/kahst/BirdNET), but this is not compatible with the analyzer.
