### ISSUE TITLE
Country based species list when lat, lon fails

### ISSUE THREAD

**Issue by tim-field** [kahst/BirdNET-Analyzer#174]
When I run `analyze.py` **without** `lat`, `lon`, I get a pretty good list of New Zealand birds, specifically `New Zealand Bellbird` and `Tui` which I know are present in the audio, along with a number of birds that I know aren't `Hawaii Creeper`, `Hawaii Akepa`

I thought the solution would be to generate a species list with my mircophones New Zealand lat long ( ` --lat -45.782474 --lon 170.507323` ) but I can never get that list to include `New Zealand Bellbird` or `Tui`. 

I've tried a few different lat longs around New Zealand and lower threshold values to no avail.

At this point I'm wondering if its possible to just get a species list of know New Zealand birds 🤔   Keen for any ideas here, thanks.  https://www.mohiohio.com/ ( scroll to listen to later recordings )

**Comment by tim-field** [comment]
Well for future travelers I wrote a script to pull this from here https://avibase.bsc-eoc.org/checklist.jsp?region=NZct

You should be able to adapt that to any country as required.


```JS
const cheerio = require('cheerio')

const url = 'https://avibase.bsc-eoc.org/checklist.jsp?region=NZct'

fetch(url)
  .then(response => response.text())
  .then(html => {
    const $ = cheerio.load(html)
    const birds = $('table.table tbody tr.highlight1').toArray()
    const birdList = birds
      .map(bird => {
        const scientificName = $(bird).find('td:nth-child(2)').text().trim()
        const commonName = $(bird).find('td:nth-child(1)').text().trim()
        return `${scientificName}_${commonName}`
      })
      .sort()
    console.log(birdList.join('\n'))
  })
  .catch(error => console.error(error))
  ```

**Comment by Josef-Haupt** [comment]
There is currently no built-in way to use all species in a given country. We use the data provided by eBird.
