### ISSUE TITLE
README anchors don't work

### ISSUE THREAD

**Issue by kahst** [kahst/BirdNET-Analyzer#181]
In the readme.adoc, anchors from the table of contents (toc) to the headings don't work. Seems like we need to remove

```
:sectnums:
:sectnumlevels: 2
```
because anchors on the toc are `#setup`, but GitHub renders headings as `#5-setup`. However, I like the numbered toc, so maybe there's another way to fix this.

**Comment by LimitlessGreen** [comment]
I think, this was a GitHub intern bug. I stubled over it too some time ago. But seems to be fixed now. I can click the anchors like normal.
