### ISSUE TITLE
Birdnet analyzer GUI - File name

### ISSUE THREAD

**Issue by nishantnnb** [kahst/BirdNET-Analyzer#183]
Hi,
Can you pls provide the name of the file which was loaded to Analyze. This is useful when someone wants to analyze multiple files one by one. 

thank you.
Nishant.

![image](https://github.com/kahst/BirdNET-Analyzer/assets/72615789/67ac992e-dca3-4d44-a5f0-683424de71ff)

**Comment by Josef-Haupt** [comment]
Since we currently use Gradio, this task is nontrivial. We might use custom HTML in the future.

**Comment by Josef-Haupt** [comment]
Implemented.
