### ISSUE TITLE
GUI crashes on Parallels

### ISSUE THREAD

**Issue by kahst** [kahst/BirdNET-Analyzer#186]
From Russ:

"Just downloaded the BirdNET Analyzer GUI to a VM running Windows 11 under Parallels on a Mac. When I tried to launch the GUI, it failed, with the message shown here. Can anyone here advise on whether/how there’s any way a non-programmer might fix this? Thanks!"

![Analyzer GUI FAIL](https://github.com/kahst/BirdNET-Analyzer/assets/6673450/a9e46e4d-0966-4f1e-b9b8-6b4f6511aa30)

**Comment by Josef-Haupt** [comment]
This error always happens when the zip did not get unblocked correctly.
