### ISSUE TITLE
GUI issue: shifting between Custom Classifier and all species

### ISSUE THREAD

**Issue by nishantnnb** [kahst/BirdNET-Analyzer#190]
When we change species list options from Custom Classifier to all species or vis versa, analysis results shows all species of the selected option with confidence = 1. 
It only starts working normal once we restart the GUI.

This seems to be a bug.

Thanks,
Nishant.

**Comment by max-mauermann** [comment]
Does this issue still occur in the current version? I currently can't reproduce it.
