### ISSUE TITLE
Conflicting Python versions

### ISSUE THREAD

**Issue by frowinbecker** [kahst/BirdNET-Analyzer#201]
Hi Team BirdNET,

Thank you for all your fantastic work. 

Whenever I try running analyze.py on Windows 11, the following error message is produced:

_ImportError: Module use of python310.dll conflicts with this version of Python._

I've made sure that I don't have more than one version of Python installed and have followed the installation instructions. Any recommendations would be hugely appreciated.

**Comment by Josef-Haupt** [comment]
Hi, could you send us the full error message?

**Comment by Josef-Haupt** [comment]
Seems like this has nothing to do with BirdNET.
