### ISSUE TITLE
Multiprocessing issue under ubuntu 22.04

### ISSUE THREAD

**Issue by joshctaylor** [kahst/BirdNET-Analyzer#204]
First of all thank you to everyone for your hard work creating this tool, its great to see such fast progress.

I have an issue running birdNET under ubuntu 22.04. It seems to be a global locking issue. I've tried to avoid using fork by forcing spawn in `analyze.py` which makes no difference:

`import multiprocessing as mp`
    
    if __name__ == '__main__':
        if cfg.CPU_THREADS < 2:
            for entry in flist:
                analyzeFile(entry)
        else:
            with mp.get_context("spawn").Pool(cfg.CPU_THREADS) as p:    
                p.map(analyzeFile, flist)

Oddly the docker version seems to create the same issue. Audio files are 320mb and 1 hour duration 44.1 kHz mono. I'm using an Azure VM

Has anyone encountered this and can recommend a work around?

`python ~/BirdNET-Analyzer/analyze.py --i /mnt/tempAudio/ --o ~/output  --threads 2 --slist ./species_list.txt `
reading eBird codes and labels
Load translated labels
Load species list
Species list contains 48 species
Found 9 files to analyze
PID: 10786
Analyzing /mnt/tempAudio/SMM0XXXX_20220919_025556.wav
PID: 10785
Analyzing /mnt/tempAudio/SMM0XXXX_20220919_104756.wav
PID: 10858
Analyzing /mnt/tempAudio/SMM0XXXX_20220919_124556.wav
PID: 10897
Analyzing /mnt/tempAudio/SMM0XXXX_20220919_144356.wav
PID: 10935
Analyzing /mnt/tempAudio/SMM0XXXX_20220919_164156.wav
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#187 is a dynamic-sized tensor).
Finished /mnt/tempAudio/SMM06291_20220919_164156.wav in 139.05 seconds

**Comment by tphakala** [comment]
What are you trying to accomplish here? TensorFlow Lite runtime itself has multiprocessing capability so all available threads should be assigned to tflite and not for python.

**Comment by joshctaylor** [comment]
@tphakala  thanks for the reply. I was trying to stagger when the audio files were read - so it doesn't happen all at one and saturate the bandwidth.
Any ideas of a work around?

**Comment by tphakala** [comment]
I have been working on golang based BirdNET analyzer called BirdNET-Go, can you test it and see how it performs compared to python version? I just released a new build today https://github.com/tphakala/birdnet-go/releases/tag/v0.4.4
