### ISSUE TITLE
Expanding 3 second audio limitation

### ISSUE THREAD

**Issue by reedflyfarm** [kahst/BirdNET-Analyzer#209]
Thanks for your work. I support Yellowstone National Park on a non-bird bioacoustics program (initially focused on carnivores) - more here [www.grizcam.com/crywolf]. We have our own wolf detector based on a large dataset from many years of recording in Yellowstone. However, we see advantages of folding our long-term efforts in to the BirdNET project. Aside from shorter vocalizations (barks, whimpers, yelps, snarls, growls, woas, etc), the two primary vocalizations that can be detected from up to 6km from ARU are howls (individual howls ranging from 1-5 seconds)  and chorus howls (highly modulated multiple wolf chorus averaging 90 seconds). Both of these vocalizations are extremely important to population estimates (and deterrence playbacks) for conservation management. The second limitation creates issues, as you are away, at detecting modulation nuances over time that are distinctive of wolves but at 3 seconds overlap with other species (some of which can be very common that it defeats the purpose of a classifier used against large datasets). We would love to talk more about your recommendations in the short term for using BirdNET in our scenario, and any collaboration on long-term decisions and commitment from us as a proactive beta tester.

**Comment by kahst** [comment]
Thanks for reaching out Jeff, we're super interested in expanding BirdNET for wolves - we've been trying to work with the limited data that was available online and included wolves in BirdNET, yet, I believe with the new re-training workflow, you should be able to train a decent classifier with the data you have. The 3-second input might be a limitation for howls, yet, we noticed that we can pool consecutive detections over time and thus 3-seconds might actually work. In fact, we just published a paper on wolf and coyote detection with BirdNET: https://link.springer.com/article/10.1007/s13364-023-00725-y 

I'd like to connect you with Connor, our lead ecologist, who would sure love to talk to you about a potential collaboration. Can you email me, and I'll connect you both: stefan.kahl@cornell.edu

Thanks!

**Comment by reedflyfarm** [comment]
Thanks Stefan. I sent you an email from jeff@reedfly.com today. Appreciate your work and your support of our efforts.
