### ISSUE TITLE
Year-round species missing when week specified

### ISSUE THREAD

**Issue by mrichar1** [kahst/BirdNET-Analyzer#211]
I'm not sure if this is a bug or by-design, but I've noticed that certain species which are listed as year-round do not appear in any weeks when a week filter is used.

To test this I ran `species.py --lat 55.7 --lon -3.4 --week X` 48 times, replacing X with 1-48) to generate weekly lists, as well as with `-1` to generate the year-round list, for my location in southern Scotland.

I then compared the year-round list to the first week to identify any 'filtered' species. I then took the filtered results and compared to week 2, and so on through the year to find any filtered results that never appear in any weekly list. The following are the missing species:

```
Anthus trivialis_Tree Pipit
Ardenna grisea_Sooty Shearwater
Aythya marila_Greater Scaup
Calidris minuta_Little Stint
Calidris pugnax_Ruff
Cettia cetti_Cetti's Warbler
Charadrius dubius_Little Ringed Plover
Circus aeruginosus_Eurasian Marsh-Harrier
Circus cyaneus_Hen Harrier
Coccothraustes coccothraustes_Hawfinch
Dryobates minor_Lesser Spotted Woodpecker
Falco columbarius_Merlin
Falco subbuteo_Eurasian Hobby
Gavia arctica_Arctic Loon
Hydrobates leucorhous_Leach's Storm-Petrel
Hydrobates pelagicus_European Storm-Petrel
Hydrocoloeus minutus_Little Gull
Ichthyaetus melanocephalus_Mediterranean Gull
Linaria flavirostris_Twite
Loxia curvirostra_Red Crossbill
Luscinia svecica_Bluethroat
Melanitta fusca_Velvet Scoter
Numenius phaeopus_Whimbrel
Pandion haliaetus_Osprey
Passer montanus_Eurasian Tree Sparrow
Perdix perdix_Gray Partridge
Phylloscopus inornatus_Yellow-browed Warbler
Picus viridis_Eurasian Green Woodpecker
Pluvialis squatarola_Black-bellied Plover
Podiceps auritus_Horned Grebe
Rallus aquaticus_Water Rail
Scolopax rusticola_Eurasian Woodcock
Spatula querquedula_Garganey
Strix aluco_Tawny Owl
Sylvia borin_Garden Warbler
Tringa erythropus_Spotted Redshank
Tringa ochropus_Green Sandpiper
Turdus torquatus_Ring Ouzel
```

**Comment by kahst** [comment]
We train our model with data for each week, but some training steps are made with `week == -1` which works a bit differently. We use eBird checklist frequency data for training, and for each week (when specified) we pick the value for this week from the data. For the year-round estimation, we use the maximum of all 48 values to train the model, which often results in a species list which is unique to `week == -1`. So for our model, setting week to -1 invokes a different inference mode based on maximum checklist frequency for each species, thus year-round species lists might differ from the set of all other 48 weeks.

**Comment by mrichar1** [comment]
Thanks for that explanation. I take it that there is therefore no way to set a week but not risk missing certain species? (We noticed this problem when very common species to us were absent in our original jobs - e.g. Tree Sparrow, Tawny Owl). If this is the case, could there be some notes explaining this added to the docs?
