### ISSUE TITLE
#57 Error with Protobuf model

### ISSUE THREAD

**Issue by tgruetzm** [kahst/BirdNET-Analyzer#214]
This is the same issue as #57 which still occurs with the latest 2.4 models.

I believe this is related to the following warning:

WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.

The linked issue from #57 goes into more detail, but I do think changing the way the model is saved might address this.
https://github.com/tensorflow/models/issues/8990#issuecomment-1069733488

**Comment by tgruetzm** [comment]
To reproduce, just try running BirdNET with protobuf model instead of the tflite one:
MODEL_PATH = 'checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model' # This will load the protobuf model
#MODEL_PATH = 'checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite'

**Comment by Josef-Haupt** [comment]
I tested this with the current commit and, although there are a lot of warnings, it still finished successfully.
Please try to update your analyzer and get back to us if it still doesn't work.
Closing for now.
