### ISSUE TITLE
Unable to run birdnet-analyzer (both GUI and CLI) when the folder is within a directory with Chinese characters on its path

### ISSUE THREAD

**Issue by Northurland** [kahst/BirdNET-Analyzer#220]
As title.
Feels like an encoding issue to me.

Operating system: Windows 10 (Version 22H2, 19045.3803), Simplified Chinese

Error messsage when attempting to run the CLI version (mind the Chinese characters "观鸟记录"):
![图片](https://github.com/kahst/BirdNET-Analyzer/assets/40388212/870ab751-0f7e-4797-a510-217b89faec22)

Error message when attempting to run the GUI version:
![图片](https://github.com/kahst/BirdNET-Analyzer/assets/40388212/85880886-6cc8-46e8-a376-113a36dd3359)
With no window of BirdNET Analyser showing up.

The exe files execute normally when I cut and paste the whole BirdNET-Analyzer folder to another directory with no Chinese characters on the path. The TensorFlow warning shows up either way.

**Comment by Northurland** [comment]
> The bug in your second image appears when you don't unblock the downloaded zip correctly as described in the readme. Please repeat the process and get back to us if that does not fix your issue.

Thank you for the reply!
Unfortunately I did unblock the file according to instructions - and I did it again with a fresh copy of the zip:
![图片](https://github.com/kahst/BirdNET-Analyzer/assets/40388212/88a41553-05c7-4619-82ff-732abcb8a91d)
...It... doesn't work. I do thing it's the exact error message...

**Comment by Josef-Haupt** [comment]
You can use the windows installer. Check out our releases.
