### ISSUE TITLE
Expanding 3 second audio limitation?

### ISSUE THREAD

**Issue by Wasser9** [kahst/BirdNET-Analyzer#228]
I’m not technically savvy, just a dumb question:

I've heard that Whisper AI has improved by processing audio in bigger chunks. Could a similar update enhance Birdnet Pi's accuracy, possibly reducing false positives like imitations? If so, would it be possible to extend the chunk duration beyond 3 seconds?

Thanks for your work, appreciate if very much!

**Comment by kahst** [comment]
That's an interesting thought that has crossed our minds before. We that some species have similar calls and can only be distinguished by call frequency, which would require a longer context window. We've seen a few successful attempts in BirdCLEF where some models used 30s context windows. Google Perch uses 5s and there is some upside to that too. Our former team member Shyam has done a great job in investigating temporal context for acoustic classification ([Paper](https://royalsocietypublishing.org/doi/pdf/10.1098/rsif.2021.0297)) and I believe that this kind of addition could a great way to incorporate temporal information and longer context windows. Yet, we've never tried that, but might in the future.
