### ISSUE TITLE
possible discrepancy between the number of species on a given week (species.py vs analyze.py)

### ISSUE THREAD

**Issue by fluxion-t** [kahst/BirdNET-Analyzer#229]
Hello. I am not sure whether I am not getting something right here or there is a discrepancy between the number of species considered by species.py and analyze.py.

```
python3 species.py --o list.txt --lat 41.39 --lon 2.16
```
says `Done. 249 species on list`.

```
python3 species.py --o list.txt --lat 41.39 --lon 2.16 --week 2
```
says `Done. 119 species on list`.

```
python3 analyze.py --i sample.wav --o results.txt --lat 41.39 --lon 2.16 --week 2
```
says `Species list contains 147 species`.

```
python3 analyze.py --i sample.wav --o results.txt --lat 41.39 --lon 2.16
```
says `Species list contains 276 species`.

I would really like to understand these numbers.

Many thanks.

**Comment by kahst** [comment]
Ah, good catch! `species.py` and `analyze.py` use different cut-off thresholds (0.05 and 0.03) to determine the species list. Therefore, `analyze.py` has more entries on the species list compared to `species.py`. We'll set the threshold to 0.03 for both of them to make things more consistent.
