### ISSUE TITLE
Proper forum for noob questions?

### ISSUE THREAD

**Issue by dacracot** [kahst/BirdNET-Analyzer#23]
I'm very interested in this project as a user, and have worked through an initial implementation, but of course I have many questions.  I wondering if there is an existing forum where non-technical questions can be asked and discussed.  If none yet exists, may I suggest [https://www.reddit.com/r/BirdNET-Analyzer/](https://www.reddit.com/r/BirdNET-Analyzer/).

**Comment by dacracot** [comment]
I've created the subreddit at [https://www.reddit.com/r/BirdNET_Analyzer](https://www.reddit.com/r/BirdNET_Analyzer).  (Notice the underscore rather than dash like above.). I'll try and pretty it up over the next few days.

**Comment by kahst** [comment]
Thanks, I've already added my first reply :) I'll put the link in the README so everyone knows. I'll close this issue for now.
