### ISSUE TITLE
Using BirdNET-Analyzer for Bat Calls 

### ISSUE THREAD

**Issue by arky** [kahst/BirdNET-Analyzer#236]
Is there new version of BirdNET-Analyzer that will be able to detect sounds above 15 kHz without requiring users to frequency shift their audio?

**Comment by arky** [comment]
> BattyBirdNET-Analyzer is a tool to assist in the automated classification of bat calls: [BattyBirdNET-Analyzer at GitHub](https://github.com/rdz-oss/BattyBirdNET-Analyzer)

Thank you @robinsandfort This seems to be fork of BirdNET project adapted for bat calls. Wonder if this work would ever make it back here?

**Comment by robinsandfort** [comment]
I can´t speak for Stefan and the team but this seams unlikely for now.

**Comment by kahst** [comment]
> Thank you @robinsandfort This seems to be fork of BirdNET project adapted for bat calls. Wonder if this work would ever make it back here?

Good question! Ideally, we'll be able to identify bats with BirdNET without having to compromise on the frequency range. We'll probably talk to Richard soon and see if there is a way to either transform BattyBirdNET into the main bat analyzer or feed things that he built back into BirdNET. We do absolutely acknowledge the need for reliable bat detection, and we do have it on our roadmap.

**Comment by arky** [comment]
Thank you @Josef-Haupt
