### ISSUE TITLE
Using segments to remove false positives

### ISSUE THREAD

**Issue by KalmiaLatifolia** [kahst/BirdNET-Analyzer#242]
Hello,

Thanks for all the great work you've put in to BirdNET. It is an incredibly useful tool.

I would like to be able to use the segments function to remove false positives from the results. Currently, the validation process makes you choose a balance between recall and accuracy. It would be nice to be able to manually check the detections I've decided to keep and use results that are 100% accurate.

To do this, it would be nice to have two features:
1) A setting that allows you to pull all segments above a set confidence score
2) Include the 'begin time', aka the offset from the start of the audio file, in the segment file names.

**Comment by reedflyfarm** [comment]
Perhaps my #1 stocking stuffer wish would be a UI that allowed one to group detections in to one viewable event based on a user specified setting of inter-detection "gap". E.g. if detections are withing X seconds of one another, treat it as one vocal event. My #1 would be to allow user-defined fields to be attached to the detections and then exported seperately along with the name of the original audio file that the detection came from. Sorry for asking :) I really appreciate all that you folks are doing already.

**Comment by Josef-Haupt** [comment]
The current repo includes a review tab, that allows users to seperate positive and negative segments.
