### ISSUE TITLE
Approach to NaN handling in TFJS 

### ISSUE THREAD

**Issue by Mattk70** [kahst/BirdNET-Analyzer#255]
This is unlikely to be a big issue in the context of the TFJS example, but perhaps a similar issue affects the python version too? This snippet is from main.js in the TFJS example:

```
                // Normalize values between -1 and 1
                input = tf.sub(input, tf.min(input, -1, true));
                input = tf.div(input, tf.max(input, -1, true).add(0.000001));
                input = tf.sub(input, 0.5);
                input = tf.mul(input, 2.0);
```

When you add a small number to the divisor to avoid an infinity value, you will get a large number, which is not between 1 and -1. In tensorflowjs, you should use tf.divNoNan() so n/0 returns 0. I believe the python version of tensorflow has an equivalent tf.math.divide_no_nan() function.

It's an edge case, but has caused headaches for me when analysing audio with a fade effect.

**Comment by Josef-Haupt** [comment]
@kahst Did you use tf.divNoNan?

**Comment by kahst** [comment]
> @kahst Did you use tf.divNoNan?

No :)

**Comment by Josef-Haupt** [comment]
You probably should then ;)

**Comment by Josef-Haupt** [comment]
We be fixed in the next model.
