### ISSUE TITLE
conda-forge for BirdNET-Analyzer?

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#26]
Hello! 

I was previously using BirdNET-Lite to process audio files through BirdNET via R. I wrote up an [install-BirdNET-for-Windows guide](https://cbalantic.github.io/Install-BirdNET-Windows-RStudio/) and documented some [R functions that helped me process and wrangle the BirdNET-Lite outputs](https://github.com/nationalparkservice/NSNSDAcoustics).

Now that BirdNET-Lite is deprecating, I am updating my workflows to accommodate BirdNET-Analyzer. With BirdNET-Lite, what worked to run via R was to set up a [conda environment for BirdNET](https://github.com/cbalantic/cbalantic.github.io/blob/master/_posts/2022-03-07-Install-BirdNET-Windows-RStudio.md#12-set-up-your-birdnet-conda-environment).

Now as I tinker with BirdNET-Analyzer instead, the error messages I'm getting lead me to believe that I will need to have my conda environment include the BirdNET-Analyzer-main module that I've locally installed. I'm not sure how to do this, since [conda develop seems to be deprecated](https://github.com/conda/conda-build/issues/4251). 

**My question is, would it be possible to include your releases of BirdNET-Analyzer-main on [conda-forge](https://conda-forge.org/) so that it could be easily installed to a conda environment?**  

(i.e., conda install - n birdnetenv -c conda forge birdnet-analyzer)

All of this may seem cumbersome to the more computer science-minded folks here, but I am trying to come up with well-documented ways to use BirdNET and promote access for more R-minded colleagues, collaborators, students, and interns who I work with. Apologies for the potentially uninformed question since Python is not my strong suit! It's possible there is a very easy solution if I were only using my own machine, but I'm hoping for a more portable solution so that I can easily document and explain to collaborators. 

Thank you for what you do.

**Comment by cbalantic** [comment]
Update: in terms of an easy solution on my own machine (Windows), I got BirdNET-Analyzer to run from R in a conda environment by manually copying the "checkpoints" folder and eBird_taxonomy_codes_2021E.json file from BirdNET-Analyzer-main over into the conda env folder itself. Not elegant, but it's working... and it's way faster than BirdNET-Lite!

Still curious about the conda-forge question though. Thank you for considering.

**Comment by kahst** [comment]
I have to admit that I haven't worked with Conda so far, but releasing this repo as some kind of package seems to be a neat thing. I'll have to do some digging and can't promise anything right now, but I'll try. In the meantime: We are also working on an R interface for BirdNET which we will release with this repo (hopefully very soon). Ideally, this would mitigate some of the difficulties when setting up and running BirdNET for the non-CS community. I'll keep you posted.

**Comment by cbalantic** [comment]
Hi Stefan, sounds great. Looking forward to learning more.

**Comment by Josef-Haupt** [comment]
As mentioned in the [README](README.md) the current recommended way to install this repo is using the [pypi package](https://pypi.org/project/birdnetlib/).
So it should be possible to use the pip in your environment to install the package locally.
