### ISSUE TITLE
Kaleidoscope output type not working (Gui v 1.0.0-beta1)

### ISSUE THREAD

**Issue by reedflyfarm** [kahst/BirdNET-Analyzer#266]
Kaleidoscope output type selected but selection tables are outputted instead of Kaleidoscope csv format

**Comment by kahst** [comment]
Can confirm that. Other output formats appear to work fine. We'll check. Thanks for posting.

**Comment by kahst** [comment]
Ok, I think I fixed it. However, you'll have to start the GUI from the Python environment for the changes to take effect.

**Comment by reedflyfarm** [comment]
there's no gui.py that is included with the installed windows version.

**Comment by Josef-Haupt** [comment]
Yes, to always have the up to date version you'll have to use the repository. The installed version is just a packaged snapshot of this repository.
