### ISSUE TITLE
understanding the model save mode (training)

### ISSUE THREAD

**Issue by robinsandfort** [kahst/BirdNET-Analyzer#267]
Hi everyone,
I´m testing the new 1.0.2 GUI and tried using the 
Mode save mode while training. Your help text states:
""replace" will overwrite the original classification layer and "append"
will combine the original classification lyaer with the new one."
What is this function doing? Do the label names have to match the v2.4 label names?
In my tests the labels of the last trained custom classifier were appended.
Would this allow output of the V2.4 model and the custom classifier at the same time? 
Thanks for your great work!

**Comment by Josef-Haupt** [comment]
You are correct. "append" basically means we concatenate the BirdNET and your custom classifier output.
Feel free to ask, if you have more questions.
