### ISSUE TITLE
Folder selection similar to File selection

### ISSUE THREAD

**Issue by nishantnnb** [kahst/BirdNET-Analyzer#269]
Hello,

An enhancement request. 
In the GUI, can we have folder selection browse window similar to the file selection window? It take a bit more time for selecting a folder with the current window for folder selection. 
1) It can't remember last used path
2) We can't copy & paste a path in it

e.g. File selection window which is currently used in the Single file tab ('Single file upload' or 'select classifier') is much easy to navigate....
![image](https://github.com/kahst/BirdNET-Analyzer/assets/72615789/ecb2f153-af0c-4a00-8590-5fd10ad5e363)

compared to the folder selection window used on the buttons in all other tabs.
![image](https://github.com/kahst/BirdNET-Analyzer/assets/72615789/85bc24e1-c8fd-46c7-b375-91f9928d54e7)

Thanks.

**Comment by Josef-Haupt** [comment]
I have tried to use the native dialog for folder selection, but there was some kind of problem preventing us from using it. We might have to use custom js instead. If I have the time, I'll look into it.

**Comment by Josef-Haupt** [comment]
Sadly this is not possible to implement in a satisfactory way.
