### ISSUE TITLE
Limit Results

### ISSUE THREAD

**Issue by supajason** [kahst/BirdNET-Analyzer#27]
Is it possible to filter out results that we below a threshold?

```
{
    "msg": "success",
    "results": [
        [
            "Pluvialis apricaria_European Golden-Plover",
            0.014033333333333335
        ],
        [
            "Columba livia_Rock Pigeon",
            0.0045
        ],
        [
            "Pyrrhula pyrrhula_Eurasian Bullfinch",
            0.0015666666666666667
        ],
        [
            "Branta canadensis_Canada Goose",
            0.0009999999999999998
        ],
        [
            "Parus major_Great Tit",
            0.0008333333333333334
        ]
    ]
}
```
Only return results above 0.01?

**Comment by supajason** [comment]
found it here
https://github.com/kahst/BirdNET-Analyzer/blob/2ea1949f9ae5372873a1a845cde71d29a0c2d0d5/server.py#L208

**Comment by kahst** [comment]
We could add `MIN_CONF` to the client, but then some responses would be empty. I thought it would be best if the clients decides what to do with the ranked list. What do you think?

**Comment by tdelattre** [comment]
From a scientific perspective, it's always better to get more results and just filter out what you don't need afterwards (it's pretty easy to do in R for example). At least you know what's happening, and you can compare the outputs of different filters without having to run Birdnet all over again.
