### ISSUE TITLE
Issue with GUI longitude and Latitude 

### ISSUE THREAD

**Issue by JonTron5** [kahst/BirdNET-Analyzer#270]
I can use the multiple file analyze when set to all birds. But when I switch to Local birds and set the Long/Lat setting and run the file/s it comes up error.  I have redownloaded but cant seem to get it to run using only local birds

**Comment by JonTron5** [comment]
I redownloaded the windows file. I made sure to click the unblock in properties and it now is working.

**Comment by Josef-Haupt** [comment]
Check out our newest release https://github.com/kahst/BirdNET-Analyzer/releases/tag/v1.0.2
The problem should be fixed. If not, please get back to us.
