### ISSUE TITLE
Folder selection buggy

### ISSUE THREAD

**Issue by robinsandfort** [kahst/BirdNET-Analyzer#272]
The folder selection is buggy (GUI version 1.0.2, Windows).
After selecting a folder via the "Select directory (recursive)" button (Multiple files)
nothing happens. (sometimes it takes 30 min for file to show up. 80% of cases nothing happens and  
Error: "Please select a directory." shows up.
Really strange.

Greetings from the woods,
Robin

**Comment by kahst** [comment]
That is indeed strange... I can't reproduce that. Is it the same for all folders, or do these folders have a particular subfolder structure?

**Comment by robinsandfort** [comment]
No subfolders. Just a folder with 7000-8000 audiomoth wav files. 40-50GB total.
It worked fine with the first ten folders and then got worse. I´ll have to check the work load.
Maybe some memory problem? With the comand line no problems with the same folders.
Greetings,
Robin

**Comment by kahst** [comment]
`analyze.py` and the GUI both use the same function (`utils.collect_audio_files`) to load the paths. Maybe it's an issue with showing the paths in the GUI as a list @Josef-Haupt

**Comment by robinsandfort** [comment]
That sounds possible. It took long for the file names/path to show up 
in the GUI.

**Comment by Josef-Haupt** [comment]
I suspect that Gradio does some stuff behind the scenes which takes a long time for 8k rows in the table. We might have to switch to custom HTML in the future.

**Comment by Josef-Haupt** [comment]
For now I could just display the first 100 (or smth), that might solve the problem

**Comment by kahst** [comment]
> For now I could just display the first 100 (or smth), that might solve the problem

Yes, I think that's a good path for now
