### ISSUE TITLE
GUI vs Raven Detector

### ISSUE THREAD

**Issue by maryjben** [kahst/BirdNET-Analyzer#276]
I have been working on a project with thousands of 10-minute audio files, which I initially ran through the BirdNet GUI and then used the output to confirm positive detections. I started using the Raven Pro detector instead because it seemed more efficient to open all sound files in a paged window, run the detector, and confirm positive detections in the same program. 

When using the GUI, I had set the sensitivity to 1.5 because I am looking for detections of secretive marsh birds, so I want to increase the chances of detection. However, Raven Pro has no option to adjust the sensitivity. So, how will this influence my detections? 

Has anyone used both the GUI and Raven Pro and determined which is the most efficient while still maximizing detections? 

To me, Raven seemed more efficient for large datasets. When working with the GUI, I had to open individual sound files and then the individual selection table from the GUI to confirm positive detections in Raven Pro. Is there a way to open all and iteratively cycle through the sound files and corresponding selection tables?

**Comment by Josef-Haupt** [comment]
The current version includes an option to combine alle the selection tables into one big table (currently only accessible with the GUI). So you could check that option and even use Raven with all the files and the combined selection table.

**Comment by Mattk70** [comment]
Hey @maryjben, given the kind of activity you describe, it sounds very much like Chirpity would be ideally suited to your use case. Chirpity allows you to load all your files (at least 25,000 at a time, anyway) , analyse them as a batch with BidrNET, and browse / play the results - which appear on a spectrogram in the UI. If you're interested in a few specific species, you can add a custom list, and this will allow you to minimise false positive detections whilst using a very low confidence threshold. You can read more and download Chirpity for Wondows or Mac from here: https://chirpity.mattkirkland.co.uk
