### ISSUE TITLE
Bandpass filter option not working

### ISSUE THREAD

**Issue by MZiegenhorn** [kahst/BirdNET-Analyzer#279]
Hi there,

Trying to use the bp filter option (--fmin and --fmax) with analyze.py in command line. I get the error that --fmin and --fmax are unrecognized arguments. Are these no longer settable? 

Thanks! Happy to provide additional detail if needed.

Morgan

**Comment by Josef-Haupt** [comment]
No, it's still [there](https://github.com/kahst/BirdNET-Analyzer/blob/7c6fe30231525a233217e28f3d7609bde7be7e5f/analyze.py#L501). Make sure you are using the current version.

**Comment by MZiegenhorn** [comment]
Thanks! I must have had an old version downloaded.

--Morgan


Morgan Ziegenhorn, PhD.
she/they
"*All that is in our minds is also in theirs." *- William Henry Hudson
