### ISSUE TITLE
What to do about lots of false positives?

### ISSUE THREAD

**Issue by dacracot** [kahst/BirdNET-Analyzer#28]
Created a [reddit thread](https://www.reddit.com/r/BirdNET_Analyzer/comments/ug5g2d/what_to_do_about_lots_of_false_positives/) of the same name with details.

**Comment by kahst** [comment]
Hard to tell, can you share some recordings?

**Comment by dacracot** [comment]
I've posted segments on SoundCloud for osprey and house finches from the same time frame.  Details on reddit.

**Comment by Andx667** [comment]
Lets continue the discussion on the linked reddit thread until there is enough information to create an issue to improve the BirdNET-Analyzer.
