### ISSUE TITLE
App on F-Droid

### ISSUE THREAD

**Issue by woheller69** [kahst/BirdNET-Analyzer#29]
Is the Android app also open-source?
Would be great to have it on F-Droid.

**Comment by kahst** [comment]
Unfortunately, it is not open source yet. But since we don't use any 3rd party services or analytics frameworks (esp. no Google services), I can just share the APK. You can download the latest version [here](https://tuc.cloud/index.php/s/jSas48xJTGWP4zL/download/BirdNET_v1.86.apk).
