### ISSUE TITLE
Segmentation combined with removal non-target species segments

### ISSUE THREAD

**Issue by Akseli-Ilmanen** [kahst/BirdNET-Analyzer#292]
Hi, 

Really appreciate the work you are doing here!

Do you know of any software/repositories that allow for segmentation

I have 2000 wildlife recordings of Carrion crow vocalizations (few sec - 2min long) with other bird sounds in the background. I would like to remove all the spectrogram segments which feature silence of other bird sounds, whilst only keeping the crow vocalization segments.

Is there any software that does bird species identification and tags the timestamps in the audio file/spectogram when which bird is vocalizing? Chirpity seems promising here. And if there is a way to combine the timestamp tagging with segmentation? For the segmentation, I was thinking about using [WhisperSeg](https://github.com/nianlonggu/WhisperSeg). 

Many thanks!

Best
Akseli

**Comment by MZiegenhorn** [comment]
Out of curiosity- if you run BirdNET on your vocalizations, does it classify Carrion crows vs 'other' very well? 

If you could get it to do that, it seems to me you could then just run some simple code to extract any segments tagged with Carrion crows. RavenLite also has that functionality, too (the segmentation piece).

**Comment by Mattk70** [comment]
Hi @Akseli-Ilmanen, 

Although I am not 100% sure what you are aiming to achieve, if I _do_ understand you correctly, [Chirpity](https://chirpity.mattkirkland.co.uk) will do this. The application will allow you to load your files and run an analysis across them all. Any Carrion Crow detections will be listed in the table, and you can filter the results to just show carrion crow detections. Selecting a detection in the results table will jump to the file at the point that detection was found.

Each detection will be timestamped - you have the option to show the position in the file, or the time of day for the detection. 

You can export a CSV file that lists the file, the position and time of day for the crow detections. Alternatively, you can export these detections as audio clips. The file names will have a timestamp reflecting the time of each detection.
