### ISSUE TITLE
embeddings.py only saving embeddings for last batch of audio chunks 

### ISSUE THREAD

**Issue by joshctaylor** [kahst/BirdNET-Analyzer#299]
Embeddings cannot handle files longer than 600 seconds.

this appear to be picked up from line 47:
`duration = cfg.FILE_SPLITTING_DURATION`

This appears to a bar to reduce memory use. 
From config.py line 101:

```
# Number of seconds to load from a file at a time
# Files will be loaded into memory in segments that are only as long as this value
# Lowering this value results in lower memory usage
FILE_SPLITTING_DURATION: int = 600
```

 However the code is not moving to the next 600 second big chunk.

a `chunks` list is made on line 58:
`chunks = analyze.getRawAudioFromFile(fpath, offset, duration)`

**Comment by joshctaylor** [comment]
An easy work around if memory use isn't an issue for you:

change line 58 to
`chunks = analyze.getRawAudioFromFile(fpath, offset, fileLengthSeconds)`

**Comment by joshctaylor** [comment]
found the issue. The code is not saving the result, the 200 embeddings being saved are the last 200 embeddings in the files. I'll send a PR.

**Comment by joshctaylor** [comment]
sent a PR #300

**Comment by Josef-Haupt** [comment]
Thanks, good catch.
