### ISSUE TITLE
Interpreting result of BirdNET custom classifier

### ISSUE THREAD

**Issue by athenasyarifa** [kahst/BirdNET-Analyzer#303]
Hi everyone, 

I have a general beginner question to confirm. I trained a BirdNET custom classifier to detect two song types (type A and B) in one species. My question is, can we substract the confidence level of type A from 1 and interpret the result as the confidence that the syllable is type B?

So if the result is the following:
 
```0	3.0	TYPE_A	0.8853```

then would it mean that there is 0.1147 confidence that it is a TYPE_B syllable?

Also, sometimes the classifier have overlapping detections (for TYPE_A and TYPE_B) in cases where it gets really confused between the two. How would you interpret that? 

Would appreciate any comment on this, thanks!

Best, 
Rifa

**Comment by nnbuainain** [comment]
Hi @athenasyarifa, the classifier outputs are sigmoid functions, which means the predictions for each class are independent from each other. So no, you can't subtract the confidence levels because they are independent.

**Comment by athenasyarifa** [comment]
Thanks for the tip!
