### ISSUE TITLE
BirdNET-Analyzer Windows app cannot run when installed outside user profile

### ISSUE THREAD

**Issue by msp2** [kahst/BirdNET-Analyzer#308]
After I install the BirdNET-Analyzer Windows app on a path outside my Windows user profile, the app can only open when I am logged in as an administrator. If I attempt to open BirdNET-Analyzer Windows app when logged into my normal user account, the following error dialog appears.

![BirdNET_ERROR_permission-denied_logs txt](https://github.com/kahst/BirdNET-Analyzer/assets/11218580/0b77aa44-71c7-4543-aa0c-d8f0c9ad379c)

When this happens, no new text appears in logs.txt.

I tried installing BirdNET-Analyzer both in "C:\Program Files" and in "C:\BirdNET-Analyzer".

**Comment by Josef-Haupt** [comment]
Program Files and your default C are protected directories, so it makes sense, that admin rights are required to run the exe. The BirdNET GUI installation needs write access in its install directory for redirecting the stdout to the logs.txt.

**Comment by msp2** [comment]
Can you recommend an install path that would facilitate multi-user installation of BirdNET-Analyzer?

As I understand it, the reason that user discretion for install path was added to the installer was to provide the option of installing BirdNET-Analyzer on a path accessible to all Windows users. This improvement is needed in university computer labs so IT staff can install BirdNET-Analyzer for all users of each machine.

**Comment by msp2** [comment]
Hi Joseph,

Thank you for responding to my support request.
Can you recommend an install path that would facilitate multi-user installation of BirdNET-Analyzer?
As I understand it, the reason that user discretion for install path was added to the installer was to provide the option of installing BirdNET-Analyzer on a path accessible to all Windows users. This improvement is needed in university computer labs so IT staff can install BirdNET-Analyzer for all users of each machine.
-Mike

_________________________________________
Michael Pitzrick (he/his/him)
Raven Support
Cornell University | K. Lisa Yang Center for Conservation Bioacoustics
159 Sapsucker Woods Rd
Ithaca, NY 14850
Office: 607-254-2124
Cell: 607-342-5415
K. Lisa Yang Center for Conservation Bioacoustics<https://www.birds.cornell.edu/ccb/>
Raven Sound Software<https://www.ravensoundsoftware.com/>
Cornell land acknowledgement<https://cals.cornell.edu/land-acknowledgment>

**Comment by Josef-Haupt** [comment]
Ah I get it, let me see if I can fix that

**Comment by msp2** [comment]
One possible solution might be to write the log to the current user profile, even when the app is installed on another path.
