### ISSUE TITLE
Creating a custom python script to use tflite model files : newby 

### ISSUE THREAD

**Issue by feiticeir0** [kahst/BirdNET-Analyzer#312]
Hi ! 
This is not a bug, but a request for help or a small tutorial to use the tflite model file on a custom python script. 

I'm trying to develop a custom script to record some bird noises and try to pass them to be interpreted by the model using tensorflow lite. 

Is there any place to look for a beginners tutorial or something like that ?  just a small snippet would be great. 

I did try something, but I'm getting a result like this:
`[-17.070267 -16.74304  -14.22112  ... -12.666912 -13.033941 -10.082461]`

after sending the numpy array to the model for a prediction. 
I'm assuming that is not right. 

Thank you for any help.

**Comment by Josef-Haupt** [comment]
The output of your classifier has no sigmoid applied to it.
See [our code](https://github.com/kahst/BirdNET-Analyzer/blob/2f0df2aa46074c6966ca8ef9f8c9e8ddd4fd1285/analyze.py#L309)
