### ISSUE TITLE
Add real-time detection

### ISSUE THREAD

**Issue by msp2** [kahst/BirdNET-Analyzer#323]
Would it be possible to add real-time detection capability to BirdNET-Analyzer? This would allow users to monitor birds in real time as they are making recordings.

**Comment by tphakala** [comment]
https://github.com/tphakala/birdnet-go has realtime detection, please see if it fits your needs

**Comment by Josef-Haupt** [comment]
There are other forks and projects that provide a real-time component to BirdNET. Although we might implement something like that in the future it is currently not a priority for us.
