### ISSUE TITLE
Issue with `segments.py` Not Saving Extracted Segments

### ISSUE THREAD

**Issue by agosjuncosa** [kahst/BirdNET-Analyzer#325]
Hi everyone!

### Issue
I am currently using BirdNET-Analyzer V.2.4 through the CLI and encountering an issue with `segments.py` where no segments are saved to the output directory, despite the script processing detections correctly.

I ran `segments.py` using the following command:

```bash
python3 segments.py --audio my_example/ --results my_example/output/ --o my_example/segments/ --min_conf 0.3 --max_segments 10 --threads 4

```
The script output indicated successful processing:

Found 1 audio files with valid result file.
Found 3 segments in 1 audio files.
Extracting segments from example/soundscape.wav

However, upon checking the output folder (my_example/segments/), I found it to be empty, with no segments saved.

### What I've Tried
1. Double-checked the paths to make sure everything is correct and accessible.
2. Made sure the output directory is there and I can write to it.
3. Tried tweaking the settings like confidence thresholds and running smaller batches.
4. Tested both custom and default models to see if it makes any difference.

I noticed a post a few months back mentioning a similar issue due to changes in how R tables are generated #197. Wondering if this might be related or if the fix mentioned might help with this issue too.

Any updates or tips on what might be going wrong or how to fix it? 
Thanks in advance!

Agostina

**Comment by wiliamsouza** [comment]
Fixed here https://github.com/kahst/BirdNET-Analyzer/pull/335
