### ISSUE TITLE
v1.1.0 Windows packaged version error from command line -- No such file or directory: 'labels\\label_names.csv'

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#340]
Hi all,

I've previously had everything working smoothly with a packaged Windows version of BirdNET-Analyzer that I downloaded in January 2024. I see that a new v1.1.0 version has been released, so I'm testing whether our workflows (detailed here: https://github.com/nationalparkservice/nsnsdacoustics) will work smoothly with the new version v1.1.0. 

Currently I get the following error, which appears to be related to a missing **labels\\label_names.csv** file. 

```
WARNING:tensorflow:From keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "analyze.py", line 557, in <module>
  File "utils.py", line 66, in readLines
  File "pathlib.py", line 1134, in read_text
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: 'labels\\label_names.csv'
[1872] Failed to execute script 'analyze' due to unhandled exception!
```

I peeked inside the Programs\BirdNET-Analyzer\labels\ folder and it does not look like there is a label_names.csv file. Instead, I see a folder named V2.4 with a few dozen txt files. 

Wondering if this is a bug or if I've done something wrong in my workflow. Thank you!

Editing to add/clarify: I am encountering this error from the command line. The GUI seems to work fine when testing the same files/folders. Would love to get the command line option working again, though!

**Comment by Mattk70** [comment]
I'm just guessing here Catherine, but it looks like you selected a custom classifier option, since BirdNET-Analyzer should only be looking for for a file named "label_names.csv" in that scenario. Was that your intention? If so, you should look for the label file where you located the custom classifier.

**Comment by cbalantic** [comment]
Hi Matt, thank you. That was exactly the problem. It was an issue in my code for trying to pass a NULL value equivalent for the classifier from R syntax into Python/BirdNET.
