### ISSUE TITLE
Low-pass filter on example

### ISSUE THREAD

**Issue by mpandit3** [kahst/BirdNET-Analyzer#35]
Hello,

Do you usually apply a low-pass filter on the audio recordings? The example soundscape file has one and I am wondering why that was applied.

Thanks and kind regards,

Meelyn Pandit

**Comment by kahst** [comment]
There is no particular reason, the sample file was simply one I had lying around and deemed useful :)

However, low and high-pass filtering might have an effect on the results, and might still be worth investigating (esp. when looking for birds in a certain frequency range).

**Comment by mpandit3** [comment]
Interesting, thanks for the info!
