### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by jmhatch** [kahst/BirdNET-Analyzer#358]
**Describe the bug**
I'm trying to run BirdNET-Analyzer on some *.wav files from an audiomoth, but I get an IndexError.

**To Reproduce**
For the CLI provide us with the arguments used.
```BirdNET-Analyzer.exe --i "20240512_083000-1.wav"```

Below is a zipped folder with the *.wav file.
[20240512_083000-1.zip](https://github.com/user-attachments/files/15875716/20240512_083000-1.zip)

**Expected behavior**
BirdNET-Analyzer would run and I'd get a selection table similar to the one shown in the /example.

**Screenshots**
```
WARNING:tensorflow:From keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "analyze.py", line 654, in <module>
  File "analyze.py", line 359, in analyzeFile
  File "analyze.py", line 318, in get_result_file_name
IndexError: string index out of range
[12496] Failed to execute script 'analyze' due to unhandled exception!
Species list contains 6522 species
[1] 1
```
**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 22H2

**Additional context**
I tried to uninstall / reinstall (following instructions from [here](https://github.com/kahst/BirdNET-Analyzer?tab=readme-ov-file#setup-windows)) with no luck.

**Comment by Josef-Haupt** [comment]
Should be fixed in the current repo, and will be included in the next release. Thanks for reporting!
