### ISSUE TITLE
V2.4 Labels are not translated for some languages

### ISSUE THREAD

**Issue by LSMSugai** [kahst/BirdNET-Analyzer#365]
Some of the label for common names are not translated from english.
For instance,

https://github.com/kahst/BirdNET-Analyzer/blob/main/labels/V2.4/BirdNET_GLOBAL_6K_V2.4_Labels_ar.txt
https://github.com/kahst/BirdNET-Analyzer/blob/main/labels/V2.4/BirdNET_GLOBAL_6K_V2.4_Labels_pt.txt

**Comment by Josef-Haupt** [comment]
We pull all the names from eBird, if there is no translation it fallsback to english (see [translate.py](https://github.com/kahst/BirdNET-Analyzer/blob/main/translate.py)). For missing translations we have to rely on local experts (like in this [pull request](https://github.com/kahst/BirdNET-Analyzer/pull/359/files)).
