### ISSUE TITLE
Error when adding arg --slist in analyze.py

### ISSUE THREAD

**Issue by Joerg-Albrecht** [kahst/BirdNET-Analyzer#370]
Dear developers of BirdNet-Analyzer,

I recently installed BirdNET-Analyzer from the github repository on MacOS (M1) as described in the help on the github page of [BirdNet-Analyzer](https://github.com/kahst/BirdNET-Analyzer?tab=readme-ov-file#setup-macos).

When running one of the examples of `analyze.py` that included the argument for providing a species list `--slist` to the function the script file produced an error. Below I copied the example code and the corresponding error.

Code:
```
python3 analyze.py --i example/ --o example/ --slist example/ --min_conf 0.5 --threads 4
```

Error message:
```
Traceback (most recent call last):
  File "/Users/joerg/BirdNET-Analyzer/analyze.py", line 583, in <module>
    cfg.SPECIES_LIST_FILE = os.path.join(script_dir, args.slist)
                                         ^^^^^^^^^^
NameError: name 'script_dir' is not defined
```

I followed the error and found that line 583 of the script file `analyze.py` (NOTE: on the github repository it is line 587) contains a BUG, because the constant `script_dir` should be replaced by `SCRIPT_DIR`. I modified line 583 of the script file `analyze.py` on my system to

```
cfg.SPECIES_LIST_FILE = os.path.join(SCRIPT_DIR, args.slist)
```

After the modification, the script ran without errors.

All the best,

Jörg

**Comment by kevtolan** [comment]
I was having the same issue and this resolved it. Thanks!

Kevin

**Comment by Josef-Haupt** [comment]
Thanks for reporting! If you want to you can always commit a PR for stuff like this, but no worries.
