### ISSUE TITLE
Dawn Chorus

### ISSUE THREAD

**Issue by Bengt** [kahst/BirdNET-Analyzer#378]
In case you didn't notice, there is the Dawn Chorus citizen science project:

https://dawn-chorus.org/

They do AI-supported bird call recognition with BirdNET:

https://dawn-chorus.org/on-ai/

**Comment by Bengt** [comment]
Should this be listed as a community project in the read me file?

**Comment by Josef-Haupt** [comment]
Thanks, Dawn Chorus is now in the project list.
