### ISSUE TITLE
Allow more than one filetype for outputs-selection checkbox allow multiple outputs instead of radio button

### ISSUE THREAD

**Issue by gcaha** [kahst/BirdNET-Analyzer#379]
I would like to output a .csv and Audacity filetypes during the same run.  Is it possible to change from radio buttons to selection checkbox that allows more than one output for each run?

**Comment by Josef-Haupt** [comment]
That is on our roadmap, can't see when it will be merged though.

**Comment by Josef-Haupt** [comment]
The current repo allows you to, to combine any output types, also as a single file if needed.
