### ISSUE TITLE
Batch Analysis mode: File with sampling frequencies >48 kHz not recognized

### ISSUE THREAD

**Issue by Richterskala101** [kahst/BirdNET-Analyzer#390]
**Describe the bug**
It is not possible to load files into input field. When trying to add folders, or drag-and-drop multiple files in the input field, the files are not processed and recognized. Therefore, no batch analysis is possible. Files with more than 48kHz sampling frequency are not processed or even recognized by the input field.

**To Reproduce**
For the GUI:
1. Go to Batch analyis tab
2. Click on Select input directory
3. search for folder with files of interest and select
4. click ok
5. Nothing happens, no files appear where they are normally listed.
For the CLI provide us with the arguments used.

**Expected behavior**
List of files/Paths would appear after selecting them

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by Josef-Haupt** [comment]
I created some test files above 48kHz but I can't reproduce your problem. Could you provide more information?

**Comment by Richterskala101** [comment]
> I created some test files above 48kHz but I can't reproduce your problem. Could you provide more information?

Thank you for looking into it. I Am trying to analyze files (preferably around 4000 per run/folder). However, once I select the folder with the files in it to analyze it takes just really long for the GUI to "recognize" or list the files. I tried it just now again with a folder with fewer files in it, which worked. With folders with a lot of files in it (~4000), it takes some minutes. Therefore, it seemed I was just not patient enough. Very sorry to open this issue gratuitous.

**Comment by Josef-Haupt** [comment]
Interesting, that was my guess as well, I'll change the GUI to show that something is being done in the background.
