### ISSUE TITLE
Sourcing Directory in BirdNet under Batch Upload not Working

### ISSUE THREAD

**Issue by Wwelsh1** [kahst/BirdNET-Analyzer#395]
**Describe the bug**
Batch files do not load under the input directory (recursive). Certain folders will populate and are able to be analyzed, but other folders, some with fewer files and others with more files, are not located by the software. For example, a folder with 3,000 flac files was successfully analyzed, but for a folder with 2,800 files, no files were found by Bird Analyzer. 

**To Reproduce**

I am not sure if this behavior can be reproduced on another device. It may have something to do with processing power, memory, or anti-malware programs. 

**Expected behavior**

I expected Bird Analyzer to be able to locate and analyze 2,800 files if it was able to find and analyze 3,000. 

**Screenshots**
<img width="154" alt="3,000 Files in Folder" src="https://github.com/user-attachments/assets/2e9af1af-943e-48fd-90d4-93d08ddc532b">
<img width="93" alt="3,000 Files" src="https://github.com/user-attachments/assets/85d6892e-2ad7-41c9-b9eb-bbb2d05d4be3">
<img width="339" alt="Bird Net Files Found" src="https://github.com/user-attachments/assets/3f50cf01-9fd4-48d9-b967-392a34435c18">
<img width="87" alt="2,800 Files" src="https://github.com/user-attachments/assets/016befc6-0d70-4e13-a8f3-303e2c2f50af">
<img width="349" alt="No Files Found" src="https://github.com/user-attachments/assets/5b5f02d0-5b8b-420a-a7e3-5f983623856c">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Win10]   
 - Version [e.g. 1.0.2]

Windows 10 Enterprise, version 22H2

**Additional context**
I have also tried folders with varying numbers of files and there seems to be no pattern to what Bird Analyzer can locate and what it cannot. It could locate a folder with 1,200 files, but not a folder with 900. I am confused about what is stopping it in certain situations. Files do not seem to be corrupted, and the folders are saved to my device's hard drive.

**Comment by Sunken-Past** [comment]
Hi there! I have the same issue. It is confusing because whereas my files are hours long and WAY fewer (folders with only 10–15 files, for instance), it works 2/3 of the time like clockwork. I tried re-arranging the files from subfolders not reachable by their recursive inputs BUT BirdNET never works with the folders it previously "couldn't find" using the batch files. Almost like it remembers. I'm going to keep troubleshooting, but this is annoying! Hopefully, they have a workaround or just some general rule. Are there ANY known limitations to file size or number of files? 

I would even be willing to process single files, but that option has never really worked for me either . . .

**Comment by Wwelsh1** [comment]
Huh, I am glad someone else has experienced the same problem. It is frustrating for me too because ideally, I'd like to analyze 20,000 files at once. My recordings are 5 days long. BirdNET does seem to remember folders that it has already found. It can continually find and analyze those when it cannot find others. I am unsure about limitations to file size or number of files, but for me it has not been able to find any folders with over 3,000 files.

**Comment by Sunken-Past** [comment]
Reddit proved somewhat helpful in explaining why this happens: https://www.reddit.com/r/BirdNET_Analyzer/comments/1cv61lp/trouble_recognising_folder/

You will **not** enjoy the solution given the insane amount of files you're trying to process!

**Comment by Wwelsh1** [comment]
Thanks for providing a solution. It's much appreciated. Is the fix to delete the empty files? I looked through all of my files (surface level at least) and they all seemed to be around the same size (200-400 KB).

**Comment by Sunken-Past** [comment]
They may be the same size, but check the last file as it seems to have been created through some dying error on part of the ARU. The last file is my subfolders is consistently "empty" in terms of SOUND, despite having a data size and not appearing corrupt. 

Hoping this helps you! :)

**Comment by Mattk70** [comment]
You might also give Chirpity a go, it handles large numbers of files and you can do your analysis using the BirdNET model. It's also much quicker to complete the analysis than using the BirdNET GUI. Chirpity is available here: https://chirpity.mattkirkland.co.uk

**Comment by Wwelsh1** [comment]
Thanks for the help y'all. I was looking through the files that Bird Analyzer was not able to find and the last file in every folder did have sound. Lots of crickets and a Tufted Titmouse. I can give Chirpity a try. Thanks for suggesting it!

**Comment by Josef-Haupt** [comment]
Fixed in https://github.com/kahst/BirdNET-Analyzer/pull/389 around 3 weeks ago
