### ISSUE TITLE
Puerto Rican Coqui frog identified with 99%-100% as Puerto Rican birds

### ISSUE THREAD

**Issue by frederickjh** [kahst/BirdNET-Analyzer#406]
**Describe the bug**
On a whim I tried whoBIRD, that uses this library, at night when the, here in Hawaii invasive, Puerto Rican Coqui frog is active. I was getting hits for nocturnal Puerto Rican birds some 99% - 100%. I think this happened before the app had my location as then it stopped. 

I then enabled "Ignore location and date" and then I got many hits for nocturnal Puerto Rican birds. I am wondering if the sounds of the  Puerto Rican Coqui frog is also in these birds' recordings and that is why this is happening.

**To Reproduce**
Using the whoBird app:
1. Play the sound of a Puerto Rican Coqui frog or travel to a place that has them and wait for night fall. Don't worry you will know them when you hear them.
2. Open the whoBIRD app and tap the microphone icon to start identifying birds
3. Uncheck the "Ignore location and date"
4. Note the many hits for Puerto Rican birds

**Expected behavior**
The data library should either identify the Puerto Rican Coqui frog (like it does for the spring peeper) or ignore the sound.

**Screenshots**
![Screenshot_20240811_215343_whoBIRD](https://github.com/user-attachments/assets/61f2ead0-2ba7-479b-a06f-b5313eb92a1b)

**Desktop (please complete the following information):**
Not using desktop

**Additional context**
Nothing to add.

**Comment by woheller69** [comment]
as long as the whoBIRD does not have your location or if the "ignore location and date..." is set, the meta model is not applied.
If the meta model is active only birds are identified. Without meta model also some other animals like frogs or wolves may be found.

**Comment by max-mauermann** [comment]
I assume the comment from @woheller69 answers this issue.

From what i can tell the coqui frog (i assume the scientific name is "Eleutherodactylus portoricensis") is not included as a species in the birdnet model.
If they are generally active at the same time as the puerto rican owl, it might be that training data included the frog in the background and so the model confuses them.

**Comment by frederickjh** [comment]
In any case, with location data on this will affect people at night in Puerto Rico and not me in Hawaii. That is the reason I did not push the point. I also figured the can search the closed issues and find this one if it affects them.
