### ISSUE TITLE
F-droid APK

### ISSUE THREAD

**Issue by FilLupin** [kahst/BirdNET-Analyzer#41]
Hello,
would it be possible to make Birdnet available on f-droid ?
It would allow users to download an up to date APK event if users do not have a google account

Regards

**Comment by kahst** [comment]
For APK download, please see #29. We are currently not planning to put BirdNET on F-Droid due to the build process requirements of F-Droid, but we might at some point in the future.

**Comment by woheller69** [comment]
which build process requirements are a problem?

**Comment by woheller69** [comment]
Of course the code must be open source. You can push it to Github and F-Droid will build it from there.
Are you using an API Key to protect your API?
I have an open issue on F-Droid regarding protection of API Keys that could need some support...

    https://gitlab.com/fdroid/fdroiddata/-/issues/2654

**Comment by kahst** [comment]
No, no API keys, but publishing the source code would drastically lower the barriers to reverse engineering...

**Comment by tommy4st** [comment]
We made the analyzer public, but we don't plan to open source the BirdNET app.
