### ISSUE TITLE
Type errors in analyze.py, audio.py and config.py at the Verify step in MacOS install

### ISSUE THREAD

**Issue by OConnorStP** [kahst/BirdNET-Analyzer#410]
**Describe the bug**
I'm walking through a CLI re-install in a new directory.  All is fine until I ran the command in the Verify step (" python analyze.py ") at which point I got this response:

(venv-birdnet) ~/Documents/Projects/Birdnet/BirdNET-Analyzer % python analyze.py                                        
Traceback (most recent call last):
  File "/Users/mikeoconnor/Documents/Projects/Birdnet/BirdNET-Analyzer/analyze.py", line 15, in <module> import audio
  File "/Users/mikeoconnor/Documents/Projects/Birdnet/BirdNET-Analyzer/audio.py", line 5, in <module> import config as cfg
  File "/Users/mikeoconnor/Documents/Projects/Birdnet/BirdNET-Analyzer/config.py", line 110, in <module>
    RESULT_TYPES: set[str] | list[str] = {"table"}
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

**To Reproduce**
For the GUI:
For the CLI provide us with the arguments used.

See above

**Expected behavior**

I wasn't expecting to see errors -- don't know what the proper response would have been

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Win10]
 - Version [e.g. 1.0.2]

MacOS Ventura 13.9.7 on an M1 Ultra

**Additional context**

**Comment by OConnorStP** [comment]
UPDATE:  Here's a Dropbox link to a terminal session where I start from an empty directory and replicate the error (having restarted the Mac)

https://www.dropbox.com/scl/fi/kg8qkkjhbuqjkua268v5g/CLI-install-session.txt?rlkey=plgx9obj9lw4d353v2f61v3kk&dl=0

**Comment by Josef-Haupt** [comment]
The Analyzer repository requires Python 3.10.
Please check your used Python version (`python --version`).
I'll make a note in the readme.

**Comment by OConnorStP** [comment]
Hi Josef,

Ah, you're right - I have Python 3.9 on this machine.  Interestingly the first time I installed Birdnet (a couple days before the one that failed) it ran fine.  Did something change recently that might have caused the 2-or-3-day-later install to fail?

Second question -- can I take your comment to mean "3.10 or later," or "3.10 only"?

Thanks for your help!

**Comment by OConnorStP** [comment]
Here's an update -- upgrading to 3.10 cured the error.  Thanks!

but 3.10 is old enough the Python site is discouraging people from installing it for security reasons.  Locating a Mac installer is tricky because the way Python.org lays out the "looking for a specific release?" page points to files that aren't an installer.  The highest Mac-installer release is 3.10.11 (which is located [here](https://www.python.org/downloads/release/python-31011/)).  

The Python site really wants Mac users to install the current release -- 3.12.5.  Would that break stuff in Birdnet?

**Comment by Josef-Haupt** [comment]
3.11 should work, that's the one I'm using but as you already discovered tensorflow does not yet officially support Python 3.12
