### ISSUE TITLE
Update Windows Installer in the ReadMe with v1.3.0

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#431]
I noticed the Windows installer still appears to be v1.2.0 in several places throughout the readme document. Is this meant to be updated with the v1.3.0 version? 

(However, looks like I can access v1.3.0 here at the release page though: https://github.com/kahst/BirdNET-Analyzer/releases/tag/v1.3.0).

**Comment by max-mauermann** [comment]
thanks for pointing this out, it will be updated soon.
