### ISSUE TITLE
Output file time fields are missing trailing numbers?

### ISSUE THREAD

**Issue by mikkohei13** [kahst/BirdNET-Analyzer#44]
Using either dockerized or Windows version of BirdNet, and saving output in CSV format, the "Start (s)" and "End (s)" fields seems to sometimes miss trailing zero (or other number?)

Example, rows 2, 16 and 17:

```
1018.0,1021.0,Buteo lineatus,Red-shouldered Hawk,0.1006
102.0,105.0,Turdus viscivorus,Mistle Thrush,0.2857
1020.0,1023.0,Turdus merula,Eurasian Blackbird,0.1264
1020.0,1023.0,Fulica atra,Eurasian Coot,0.1195
1022.0,1025.0,Fulica atra,Eurasian Coot,0.5702
1026.0,1029.0,Drepanis coccinea,Iiwi,0.1028
1030.0,1033.0,Dog,Dog,0.1531
1030.0,1033.0,Turdus viscivorus,Mistle Thrush,0.1335
1030.0,1033.0,Corvus corax,Common Raven,0.1332
1032.0,1035.0,Anas crecca,Green-winged Teal,0.3920
1032.0,1035.0,Anser anser,Graylag Goose,0.1338
1034.0,1037.0,Anas crecca,Green-winged Teal,0.1263
1036.0,1039.0,Turdus merula,Eurasian Blackbird,0.4798
1038.0,1041.0,Anser anser,Graylag Goose,0.4178
1038.0,1041.0,Cygnus cygnus,Whooper Swan,0.1124
104.0,107.0,Turdus migratorius,American Robin,0.2337
104.0,107.0,Turdus philomelos,Song Thrush,0.1144
1040.0,1043.0,Anser anser,Graylag Goose,0.2485
1040.0,1043.0,Cygnus cygnus,Whooper Swan,0.1544
```

Problematic fields seem to systematically have larger value on the end field than the following row: e.g. on row 2 end value should maybe be 1050.0, which is larger than the end value 1023.0 on row 3.

Occasionally the time value is even shorter, like on row 2 here:

```
1198.0,1201.0,Anser anser,Graylag Goose,0.8534
12.0,15.0,Haemorhous mexicanus,House Finch,0.1176
1200.0,1203.0,Anser anser,Graylag Goose,0.9340
```

**Comment by kahst** [comment]
It seems that this issue is related to the way how Python sorts timestamps. My guess is, the timestamps are correct and refer to seconds 102 to 105 in the first example, and simply appear in the "wrong" line. Not sure how Python does the sorting, though. Maybe this behavior is different on Windows and Linux?

**Comment by Josef-Haupt** [comment]
Not seen since, reopen if encountered again.
