### ISSUE TITLE
GUI Train error using append

### ISSUE THREAD

**Issue by larskristian02** [kahst/BirdNET-Analyzer#453]
**Describe the bug**

When using append model save mode, the trainer runs until completion, then produces the error screen along with a message "No such file or directory". No error message found in log other than a The GUI settings screen shows "no content" under error log file. 

This issue doesn't happen if i choose replace and not append.

**To Reproduce**

Go to Train
Add ten classes of .wav files.
Save as tflite file, append mode, everything else default, start training.
See error

**Expected behavior**
No error
The trained model adds data to the original BirdNET classifier

**Desktop:**
Macbook Pro M1
Version GUI 1.3.1, model V2.4
Also happened on my windows pc

**Comment by tphakala** [comment]
I am also having this issue on Windows 11, BirdNET Analyzer v1.3.1

![2024-09-30_18-09-23](https://github.com/user-attachments/assets/fb507eb8-5bf1-4db1-909b-f7ac094a679f)

**Comment by tphakala** [comment]
I found a workaround:

- Download [BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite](https://github.com/kahst/BirdNET-Analyzer/blob/main/checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite) and rename it to BirdNET_GLOBAL_6K_V2.4
- Download [BirdNET_GLOBAL_6K_V2.4_Labels_en_uk.txt](https://github.com/kahst/BirdNET-Analyzer/blob/main/labels/V2.4/BirdNET_GLOBAL_6K_V2.4_Labels_en_uk.txt) and rename it to BirdNET_GLOBAL_6K_V2.4_Labels.txt
- Load this model as custom classifier in BirdNET Analyzer
- Set your training parameters and set mode to append

This produced new model file while with contents BirdNET_GLOBAL_6K_V2.4 and my own training data, BirdNET Analyzer still produced file error and failed to create new labels file for custom classifier, but I added my missing labels to BirdNET_GLOBAL_6K_V2.4_Labels_en_uk.txt file and renamed it as CustomClassifier_Label.txt and profit! Model works.

**Comment by max-mauermann** [comment]
We got a fix for this that should be included soon in an upcoming patch release.

**Comment by tphakala** [comment]
@max-mauermann thank you for a quick fix!
