### ISSUE TITLE
.NET issue

### ISSUE THREAD

**Issue by AugustT** [kahst/BirdNET-Analyzer#46]
![image](https://user-images.githubusercontent.com/3987564/177135177-94429970-afb4-4e64-b6cd-4532d6753af8.png)

Running the GUI on windows 10 I get this error in the console. Does this make sense to anyone?

**Comment by Andx667** [comment]
has this been solved in the mean time?

**Comment by AugustT** [comment]
It has. Or it solved itself. I don't recall.
