### ISSUE TITLE
Where are BirdNET observation sound snippets saved on an iPhone?

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#47]
I'm relaying this question from someone else at the Bioacoustics Stack Exchange (currently in beta): 
https://bioacoustics.stackexchange.com/questions/114/where-are-birdnet-saved-observation-sound-snippets-saved-on-an-iphone

"I've recorded some sounds using the app BirdNET (https://birdnet.cornell.edu/) and would like to share/export some of the recorded observations I made and saved. I cannot find them within my iPhone's folder structure. Is anyone familiar with where these are saved by default or how to extract them?"

Stefan or others, if there's a better place to ask this question about the phone apps, please let me know!

**Comment by Andx667** [comment]
The reocrdings are saved inside the App-Storage. Since this is the Issue Tracker for BirdNET-Analyzer please ask App related questions on our Twitter @BirdNET_App or Reddit https://www.reddit.com/r/BirdNET_Analyzer/
