### ISSUE TITLE
proxy-settings

### ISSUE THREAD

**Issue by robinsandfort** [kahst/BirdNET-Analyzer#472]
Hi everyone,
a colleague of mine has a problem installing BirdNET-Analyzer-1.3.1-win.exe
on a network computer (windows).  After starting the Analyzer they get a message to check the proxy settings
allowing localhost. The stated line of code is "Context.root_block = None"
Any idea what could be wrong?
Greetings from the woods,
Robin

**Comment by robinsandfort** [comment]
This did solve the problem:

set http_proxy=<proxy-server-url>
set https_proxy=<proxy-server-url>
set no_proxy=localhost,127.0.0.1,::1
start "" <BirdNET-Analyzer-path>

https://github.com/kahst/BirdNET-Analyzer/issues/375

**Comment by Josef-Haupt** [comment]
Thanks for posting the solution, I will add this to the readme.

**Comment by robinsandfort** [comment]
https://github.com/kahst/BirdNET-Analyzer/issues/375#issuecomment-2279869218

This comment on issue 375 did the trick.
Greetings Robin
