### ISSUE TITLE
Running segments.py with forward slashes crashes it

### ISSUE THREAD

**Issue by Jar0000-0000** [kahst/BirdNET-Analyzer#48]
Running segments.py with forward slashes on Windows 10 leads to a system error. For example when running the example command `python3 segments.py --audio example/ --results example/ --o example/segments/ `
This seems to be caused by the code expecting backslashes (pathname splitting on line 191 doesn't work as expected).

Thanks for fixing this!

**Comment by jds3d** [comment]
This appears to have been fixed.  I am using forward slashes, and line 191 looks like it uses ".split(os.sep)".
