### ISSUE TITLE
UK species list does not work on run.bat

### ISSUE THREAD

**Issue by Adamtcurry** [kahst/BirdNET-Analyzer#49]
Hi there, 

if i run the run.bat file with the uk species list i get this error

"""D:\BirdNET-Analyzer>BirdNET-Analyzer.exe --i "E:\site_1_orange\s1june10pm.WAV" --o _soundfile_data\_s1june10am --slist labels\V2.1\BirdNET_GLOBAL_2K_V2.1_Labels_uk.txt

Traceback (most recent call last):

  File "analyze.py", line 389, in <module>

  File "analyze.py", line 65, in loadSpeciesList

  File "encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 582: character maps to <undefined>

[13944] Failed to execute script 'analyze' due to unhandled exception!

 

D:\BirdNET-Analyzer>pause

Press any key to continue . . .""""

It's very odd as the other species lists work fine and they only seem to be txt files with very little to no difference.

**Comment by Adamtcurry** [comment]
Also what is the difference between the species lists? the uk one has 2434 species in it? so maybe it's not what i thought it was?

**Comment by Adamtcurry** [comment]
That was the ukranian language list.... my bad.

**Comment by kahst** [comment]
Yes, UK is the Ukrainian list of translated labels and should be used through `--locale uk` and not `--slist`. I added UTF-8 as default encoding when loading label or result files; hope that fixes it.
