### ISSUE TITLE
Parus major being identified as Fringilla coelebs

### ISSUE THREAD

**Issue by tphakala** [kahst/BirdNET-Analyzer#496]
**Describe the bug**
Attached audio clip is of Parus major (great tit), however BirdNET model 2.4 reports it as Fringilla coelebs (common chaffinch) with 0.89 confidence, or even high as 0.96 with higher overlap values.

![image](https://github.com/user-attachments/assets/e51cd72a-2e8d-46a4-bccf-42086a4e8ece)

[fringilla_coelebs_96p_20241031T092716Z.zip](https://github.com/user-attachments/files/17590443/fringilla_coelebs_96p_20241031T092716Z.zip)

Interestingly Merlin app is identifying this same clip as both common chaffinch and great tit, maybe there is error in Xeno Canto source data?

**Comment by kahst** [comment]
Yeah, both species have a very similar sounding call - we know this is something that confuses BirdNET. Interesting to see that Merlin struggles too..
