### ISSUE TITLE
Playback segment error - following Single Analysis. 

### ISSUE THREAD

**Issue by timboucher** [kahst/BirdNET-Analyzer#528]
**Describe the bug**
When you are finished analyzing (single analysis), and you have got your results - you can click on each call event and listen to it. Unfortunately, the calling segment does not line up with the call time, and you hear a totally different time segment. 

**To Reproduce**
For the GUI:
1. In Single Analysis, load a WAV file
2. Go to the results from "Analyze"
3. Click on each time segment to listen to it
4. Error - a different time segment plays. Verified using Audacity to check the segment. 

**Expected behavior**
The incorrect segment plays, causing confusion. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version 15.1

**Comment by Josef-Haupt** [comment]
Yes, you are right, there is a formatting error, thanks for reporting!

**Comment by Josef-Haupt** [comment]
Just released a new version that should include the fix.

**Comment by timboucher** [comment]
Hi – maybe you can help me with some recommendations on analyzing a short recording? It’s from the Isiola region in Kenya (northern Kenya), and you can easily hear a red-chested Cuckoo (~2000 hz) and a ring-necked dove (800 Hz).  I used species by location (37E, 0N). I have attached the recording. I used Wildlife Acoustics Micro.

When I run Birdnet analyzer, the cuckoo gets easily picked up (high confidence) but the ring-necked dove does not (only at the very end). Any suggestions on how to tweak the settings to both get picked up? Is it because the dove is calling at the same time as the cuckoo (and is a little softer)? Maybe using the min and max bandpass frequency would help?

[there are a few other species – like rattling cisticola (30s – 5000 hz), diderik cuckoo at 7000 Hz 0 – and other species  - but softer.]


Also, please explain a little what changing sensitivity does?

Thanks for your help!
Tim



Cheers
Tim



From: Tim Boucher ***@***.***>
Date: Tuesday, December 17, 2024 at 8:03 AM
To: kahst/BirdNET-Analyzer ***@***.***>
Subject: Re: [kahst/BirdNET-Analyzer] Playback segment error - following Single Analysis. (Issue #528)
When will the new/corrected version be posted?

Thanks!

Cheers
Tim



From: Josef Haupt ***@***.***>
Date: Tuesday, December 17, 2024 at 8:01 AM
To: kahst/BirdNET-Analyzer ***@***.***>
Cc: Tim Boucher ***@***.***>, Author ***@***.***>
Subject: Re: [kahst/BirdNET-Analyzer] Playback segment error - following Single Analysis. (Issue #528)

Closed #528<https://github.com/kahst/BirdNET-Analyzer/issues/528> as completed via #530<https://github.com/kahst/BirdNET-Analyzer/pull/530>.
