### ISSUE TITLE
Selection Table Output & Raven

### ISSUE THREAD

**Issue by PenguinPeeps** [kahst/BirdNET-Analyzer#535]
BirdNET appears to be exporting the .txt selection tables in a format that Raven Pro 1.6 cannot read (the output settings are selected for Raven). I believe the issue is missing delimiters in the text files - Raven requires a comma or slash between column names. This is a rather tedious issue when trying to review the batch analysis from BirdNET in Raven. Is there a way for me to resolve this that avoids having to manually edit each text file?

Here is the error I get when trying to open BirdNET output selection files or combined tables in Raven:
![raven_import_error](https://github.com/user-attachments/assets/3d1fdd7a-7019-47ef-b29b-cdb07cf71a2f)

And an image of a text file output from BirdNET:
![image](https://github.com/user-attachments/assets/18f2c04f-e4c3-419d-b47b-c74578c619a3)

**Comment by Josef-Haupt** [comment]
How did you resolve this issue?
