### ISSUE TITLE
The listing of specific birds are in english.

### ISSUE THREAD

**Issue by sebvdn** [kahst/BirdNET-Analyzer#537]
![Capture d'écran 2024-12-29 080558](https://github.com/user-attachments/assets/5b50cc8b-bfab-4c43-93d3-964d06a5c47b)

The list of bird sound results is in English, although the entire interface is in French.

**Comment by tphakala** [comment]
To me this does not look like a screenshot of BirdNET Analyzer, are you sure you filed your issue ticket to correct repository?

**Comment by sebvdn** [comment]
> To me this does not look like a screenshot of BirdNET Analyzer, are you sure you filed your issue ticket to correct repository?

It's true lol !
