### ISSUE TITLE
Species probability classes

### ISSUE THREAD

**Issue by Ybema** [kahst/BirdNET-Analyzer#54]
I'm curious to learn about the probability class definition; where are they defined and on which basis? Is there any (scientific) documentation on that?

**Comment by Josef-Haupt** [comment]
I'm not sure I can follow. If you have further information, let us know

**Comment by Andx667** [comment]
As an addition: on the bottom of https://birdnet.cornell.edu you can find all scientific publications about BirdNET - thats all the scientific documentation that is available.

**Comment by Ybema** [comment]
Thanks for replying. What I meant is the definition of classification categories: "Almost certain", "Highly uncertain", "uncertain" etc.: which ranges of uncertainty are you using for the app? Is there any documentation on that?

**Comment by max-mauermann** [comment]
The probabilities of the categories should be the following:

Almost certain: >= 85 %
Highly likely: >= 65 %
Likely: >= 25%
Uncertain: >= 5%
Highly uncertain: >= 1.5%
Only a wild guess: < 1.5%
