### ISSUE TITLE
Please add Begin.File info to the selection tables?

### ISSUE THREAD

**Issue by tdelattre** [kahst/BirdNET-Analyzer#58]
Hi Stefan and dev team,
The new BirdNET-Analyzer is a marked improvement over the previous version so far, thanks very much for your work!
However, there is a small snippet that disappeared which makes my work far more difficult (and I'm sure others too). 
The selection table files don't have Begin.File info anymore. This was really useful for batch processing data in R because it allowed for easy extraction of the exact date, time and recorder name from the file name.  Do you think you could add that back without too much of a hassle?
Thanks a lot!
Thomas

**Comment by Josef-Haupt** [comment]
I can not find any documentation on this format.
If anyone could provide me with instructions, I'll implement this as an option.

**Comment by Josef-Haupt** [comment]
As far as I know, `Begin.File` is just another column which contains the file name.
I'll implement exactly that, let me know if I understood it wrong.
