### ISSUE TITLE
Question: what dataset is used to train the current BirdNET model?

### ISSUE THREAD

**Issue by Northurland** [kahst/BirdNET-Analyzer#60]
Hello BirdNET team.
I am a contributor of eBird and use your tool a lot！I wonder if the sound recordings uploaded to eBird (i.e. to Macaulay library) are part of your dataset used - or, if I upload recordings, am I technically helping the improvement of this tool? If so, does the high-quality recordings help more or low-quality ones are equally important?

**Comment by kahst** [comment]
Yes, uploading data to eBird and Macaulay Library helps to improve BirdNET. We're suing quite a few data sources, but Macaulay Library and Xeno-canto are the two largest collections we use. Thanks for contributing!
