### ISSUE TITLE
list of non-avian labels

### ISSUE THREAD

**Issue by heteralocha** [kahst/BirdNET-Analyzer#64]
Hello! 

Thanks so much for the incredible resource of BirdNET. In addition to birds, my organization is curious about all of the non-avian sound sources BirdNET can now apparently identify (e.g., we now get engine, various amphibians, coyote, etc.). I went into some of the labels files and I know the possible labels are all there, but I was wondering if there is some easy way to find a list specifically of just the non-avian sounds BirdNET Analyzer can label, so I can bring this information to others. Apologies if this is easily accessible already and I'm just missing it! Any direction is much-appreciated.

Thanks

**Comment by Josef-Haupt** [comment]
Duplicated in #67
