### ISSUE TITLE
"Error: Cannot open audio file ..." on some mp3 files, but not others.

### ISSUE THREAD

**Issue by cbalantic** [kahst/BirdNET-Analyzer#65]
I'm running BirdNET Analyzer from the command line in Windows, and can't figure out the following strange problem. I have a folder full of mp3 files all from the same audio recorder. BirdNET Analyzer processes many of them, but not all of them. For the audio files it doesn't process, it gives the error: 

Analyzing E:\xxxxx\fiilename.mp3
Error: Cannot open audio file E:\xxxxx\fiilename.mp3

I've tried moving the offending files to different folder locations (such as local to my machine in case it was some type of connection issue with the external hard drive), but the error persists only for specific files. The files producing this error are not too short, they open fine in Audacity and other programs, and don't seem to be corrupt or have any obvious issues. BirdNET-Analyzer runs fine on these files if I convert them to wave first, but I'd rather avoid this workaround to mitigate size/storage challenges. Has anyone run into this, and do you know of a workaround?

**Comment by nilspupils** [comment]
I have the same problem. Would be great if someone could clear this up.

**Comment by kfristrup** [comment]
I recommend comparing the "metadata" embedded in the MP3 files (working versus not). "MP3" supports heterogenous formats, and it seems likely that the MP3 front end for BirdNET chokes on some of them.
Your probable solution will be to use something like ffmpeg to convert the problematic files to a kinder, gentler version of MP3.
my 2c,
kurt

**Comment by tommy4st** [comment]
As we use `librosa` for audio processing, that's probably the right place to figure out the problems with your specific MP3 files. There's maybe an issue with some uncommon MP3 coding parameters like variable bitrate.
