### ISSUE TITLE
Questions: About the parameters overlap and sensitive

### ISSUE THREAD

**Issue by Roarrrrrrr** [kahst/BirdNET-Analyzer#66]
Hi BirdNET team, 

Thank you so much for your work. I am new to BirdNET, and I am wondering how the parameters "overlap" and "sensitive" affect the results. I tried different "overlap" and got different results. Is the "overlap" means the minimum time interval between to detected species? And about the "sensitive," what is the interaction between "sensitive" and confidence in the result?

Thank you in advance!

Liufeng

**Comment by abfleishman** [comment]
@Roarrrrrrr My understanding is that overlap is purely the overlap between windows.  Overlap of 0 is independent windows.  overlap of 1 is a 1-second overlap between adjacent windows. See this link https://github.com/kahst/BirdNET-Analyzer/blob/main/analyze.py#L358

**Comment by kahst** [comment]
Yes, @abfleishman is correct, overlap defines overlap between windows. Sensitivity impacts the slope of the sigmoid activation function of the last layer, resulting in more detections with increased sensitivity.
