### ISSUE TITLE
Capital letter missing for species of Nordic countries!

### ISSUE THREAD

**Issue by Svardsten53** [kahst/BirdNET-Analyzer#70]
Please adjust the species lists for Sweden, Norway and Finland so that each species begins with a capital letter.

Example: Dryobates minor_mindre hackspett  --->  Dryobates minor_**M**indre hackspett

Please note that only the first word of the species name should be capitalized.

Thanks!

**Comment by Josef-Haupt** [comment]
@kahst Is this the recommended way? If so, I could check alle the labels based on this pattern and correct them.

**Comment by kahst** [comment]
Yes, it should be capitalized. However, we might need to do that in `translate.py` to make it future-proof.

**Comment by mikkohei13** [comment]
According to Finnish grammar, species names should *not* be capitalized.

**Comment by kahst** [comment]
Ok, so we'll just leave it this way, since we're pulling names from eBird. @mikkohei13 I also merged your changes, but we'll probably have to do this again for new model versions. Seems like eBird doesn't have the additional translated names.

**Comment by Svardsten53** [comment]
I'm not really following along here. It is correct that species names should not be capitalized when they appear in a sentence, but otherwise they should be capitalized when they stand alone. I see that lowercase letters are used in eBird, but this is definitely wrong. Please change, at least in the Swedish list. Thanks!
