### ISSUE TITLE
Example usage not working

### ISSUE THREAD

**Issue by gls21** [kahst/BirdNET-Analyzer#78]
Hi,
I followed the Setup (Ubuntu) instructions included in the README. I have Python3 installed, and I also installed Tensorflow (2.11.0), librosa  (0.10.0), and ffmpeg (5.1.2), and have cloned the BirdNET repository, and navigated into it. 

When I try to run analyzer.py on your example soundscape.wav file using the code below, it returns: Error: Cannot open audio file example/soundscape.wav
python3 analyze.py --i example/ --o example/ --slist example/ --min_conf 0.5 --threads 4

![image](https://user-images.githubusercontent.com/91906620/224766580-6073f83b-3354-4504-93a2-d9eb0c7ecbfd.png)

I also get the same error when I try to run it on my own data. 

Here is my system information:

![image](https://user-images.githubusercontent.com/91906620/224767111-d2dadb10-33eb-48b8-8bdb-17371466ec2d.png)

Any help would be much appreciated, thanks!

**Comment by Josef-Haupt** [comment]
Hi! It looks like the file cannot be opened by the script. I just tried it locally and it should work. But I was able to reproduce your issue by remove the "Read" right from the `soundscape.wav` file. So check the permissions on the example directory or even the file, for some reason you might be missing the read flag.

**Comment by gls21** [comment]
Thanks for your quick response! I've checked the permissions on the soundscape.wav file, and it does appear to have read permissions?
![image](https://user-images.githubusercontent.com/91906620/225027516-f1789038-0110-49fa-b27e-3c997ab4b9da.png)

**Comment by Josef-Haupt** [comment]
As per my comment [here](https://github.com/kahst/BirdNET-Analyzer/issues/76#issuecomment-1468178938), we'll update the code to show the full error.
