### ISSUE TITLE
Windows zip has model 2.1 not 2.2

### ISSUE THREAD

**Issue by AugustT** [kahst/BirdNET-Analyzer#80]
The ready to run Windows version that you point to here: https://github.com/kahst/BirdNET-Analyzer#setup-windows Seems to be running the old 2.1 model not the newer 3k 2.2. Is there a plan to update this? Or is there a way I can load the newer model into the GUI application I am running?

**Comment by gitalm** [comment]
Dear Stefan,

thanks for the wonderful software. The newest model 2.3 isn't in the Windows *zip file. But if you install it manually, the newest model seems to be installed. 

Best wishes Johannes

**Comment by AugustT** [comment]
+1

**Comment by kahst** [comment]
We updated the Windows zip file and it should now have the newest version (model and GUI). Give it a try and let us know if you notice anything that's not working.

**Comment by r-struhs** [comment]
Hi, I am actually wanting to test out the 2.2 windows model in the windows command prompt to compare my results- is there a way to get the 2.2 model?
