### ISSUE TITLE
Using all memory and swap and then failing.

### ISSUE THREAD

**Issue by gitmatt19** [kahst/BirdNET-Analyzer#84]
I'm trying to run this against an MP3 file I recorded in the woods for ~15 hours and it is failing.
It runs for quite a few minutes and I can see the memory usage maxing out and the swap maxing out and then it just fails with the error below. I dont see any options to control/limit memory usage. 

CentOS7 with python 3.7 added. 32GB ram, 16GB swap. 8 Core CPU.

$ python3.7 analyze.py --i ZOOM0001.MP3 --o temp.txt --lat XX.45210 --lon -XXX.16474 --min_conf 0.5 --threads 4
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Species list contains 259 species
Analyzing ZOOM0001.MP3
Error: Cannot open audio file ZOOM0001.MP3

**Comment by Andx667** [comment]
for a short term fix, you can try and use a smaller input file. Maybe try halving the 15hours until it works.

**Comment by gitmatt19** [comment]
Using mp3split to create 1 hour files seems to work but you still have to set "threads" to 1 or one of the libraries still fails.

**Comment by Josef-Haupt** [comment]
This should be fixed in the current version.
