### ISSUE TITLE
Sample Rate 44,1 kHz not working

### ISSUE THREAD

**Issue by HGFestl** [kahst/BirdNET-Analyzer#85]
Hi all,

I installed BirdNET-Analyzer a few month ago on a system, and it worked fine. But now I got a new computer, installed the Analyzer also on this one. On this new system I got the error message "Cannot open file...". I found that the sample rate of 44100 Hz will not work anymore. If I convert the files to 48000 Hz, it worked fine.
Does anybody know the reason for this? 

Best regards, Hans Guenter

**Comment by alynch** [comment]
I encountered the same issue. I'm sure there is a better way to deal with it, but for now I've changed the `config.py` file:

```
-SAMPLE_RATE = 48000 
+SAMPLE_RATE = 44100
```

Regards

**Comment by bartman081523** [comment]
please try to install resampy with `pip install resampy` ?

**Comment by HGFestl** [comment]
Thank you, bartman! resampy seems to fix the problem!

**Comment by Josef-Haupt** [comment]
Thanks for helping! I added `resampy` to the install instructions, since it seems librosa needs it for some features but it's not installed automatically.

**Comment by Yaniel-Wong** [comment]
Thanks! I will have a try on newest Python cos my BirdNET only works well on Py3.8.

**Comment by Yaniel-Wong** [comment]
Thanks! I will have a try on newest Python cos my BirdNET only works well on Py3.8.
