### ISSUE TITLE
Analyze Error for .mp3

### ISSUE THREAD

**Issue by helium38** [kahst/BirdNET-Analyzer#87]
Hello! 

I am trying out your model and am running into an audio file compatibility issue. I'm able to analyze .wav and .ogg files but I'm getting an error when I try to analyze .mp3 files. I've tried trimming the .mp3 thinking that it was too big to parse but I'm still getting an error. I dropped sample files into the /example folder. Below you can see that your .wav sample runs fine as does a .ogg file that I loaded to the same path. I'm getting the error for .mp3 only. 

<img width="576" alt="Screen Shot 2023-03-29 at 8 48 59 PM" src="https://user-images.githubusercontent.com/129345044/228702316-172b99ce-4f24-439a-9529-fb85e6c8dbba.png">

<img width="394" alt="Screen Shot 2023-03-29 at 9 12 46 PM" src="https://user-images.githubusercontent.com/129345044/228702434-ee9f2f81-cb13-4a31-ae74-1a2277599511.png">

<img width="390" alt="Screen Shot 2023-03-29 at 9 08 14 PM" src="https://user-images.githubusercontent.com/129345044/228702070-7cdfe2a9-c3da-4dfd-81ca-8b068bcb0473.png">
69d-9ac0-cdda3b4aa02c.png">

**Comment by Josef-Haupt** [comment]
Hi, according to this error message your file contains data in an unknown format and thats why librosa is not able to open it.
Do you have `resampy` installed?
Also what version of librosa are you using?
