### ISSUE TITLE
tflite - python jupyter notebook 

### ISSUE THREAD

**Issue by helium38** [kahst/BirdNET-Analyzer#88]
Hello,

I am running into one more error that I haven't been able to resolve. Does anyone have any suggestions?

<img width="953" alt="Screen Shot 2023-03-29 at 9 32 42 PM" src="https://user-images.githubusercontent.com/129345044/228706211-cd701858-b236-4c13-ac43-e27daa6817ce.png">

I confirmed tf-lite is installed and double checked the config model paths. Also looked at the tensorflow support (https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) but not sure how to resolve this error. 

<img width="705" alt="image" src="https://user-images.githubusercontent.com/129345044/228705827-252a16ed-8f5e-494c-9d70-2106b7e5fb2e.png">

<img width="1017" alt="Screen Shot 2023-03-29 at 9 37 56 PM" src="https://user-images.githubusercontent.com/129345044/228706270-9498735c-a1d8-4e55-9afa-a2a5e58b8aa0.png">

**Comment by Josef-Haupt** [comment]
Hi, looks like this error is thrown, when you build your binaries with a higher version of GLIB than is used to run them.
According to this [SO question](https://stackoverflow.com/questions/74032470/version-glibc-2-29-not-found-when-using-tflite-runtime).
