### ISSUE TITLE
Installing the gui packages will install a newer numpy (1.24) and disable the analyzer.

### ISSUE THREAD

**Issue by miboka** [kahst/BirdNET-Analyzer#94]
The packages that needed to be installed for the gui to work, installed a newer version of numpy (v1.24) on my system ( I don't remember which one of the two packages). However, Analyze.py will only work with numpy at v1.21 max, and fail with newer versions.  This is on a Mac.

cheers, Michael

**Comment by Josef-Haupt** [comment]
What exactly is the problem?

**Comment by Andx667** [comment]
The Analyzer needs numpy 1.21 MAX and the GUI installs numpy 1.24 which is higher than the analyzer version.

**Comment by fegue** [comment]
I just pushed a branch with installation instructions for macOS. It installs `numpy` 1.23.2
Both the GUI and the analyzer work for me.
You could take a look at it and see if works for you too.
